<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('db.etree.org')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/images/db-logo.png'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->appendFile($this->basePath() . '/scripts/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->setAllowArbitraryAttributes(true)
                                      ->prependFile($this->basePath() . '/scripts/require-jquery.js', 'text/javascript', array('data-main' => '/scripts/main')) ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><img src="/images/db-logo.png"></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <?php
                            if ($this->zfcUserIdentity()) {
                            ?>
                            <li id="user-menu" class="dropdown">
                                <a id="user-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 24)); ?>
                                    <?php echo $this->zfcUserDisplayName() ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="user-drop" role="menu">
                                    <li role="menuitem"><a href="/user/profile">Profile</a></li>
                                    <li role="menuitem"><i class="icon-signout"></i> <a href="/user/logout">Logout</a></li>
                                </ul>
                            </li>
                        <?php
                        } else {
                        ?>
                            <li><a href="/user/login">
                                <i class="icon-signin"></i>
                                Sign In
                            </a></li>
                        <?php
                        }
                        ?>
                        </ul>

                        <ul class="nav">

                            <li class="dropdown">
                                <a id="performer-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <i class="icon-film"></i>
                                    <?php echo $this->translate('Performers') ?>
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="performer-drop" role="menu">

                                    <li role="menuitem">
                                        <form class="navbar-search pull-left" id="performer-search" action="/performer/detail">
                                            <?= $this->inputPerformer(null, 'Search'); ?>
                                        </form>

                                        <script>
                                            $(function() {
                                                $('#performer-search').on('submit', function(event) {
                                                    if ($(this).find('input[name="performer_id"]').val()) {
                                                        window.location = '/performer/detail?id='
                                                            + $(this).find('input[name="performer_id"]').val();
                                                    }

                                                    return false;
                                                });
                                            });
                                        </script>
                                    </li>

                                    <?php
                                    if (isset($_SESSION['performers']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['performers']['latest'] as $id) {
                                            if ($p = $this->findPerformer($id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/performer/detail?id=<?= $p->getId(); ?>">
                                                            <i class="icon-film"></i>
                                                            <?= $this->escapeHtml($p->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <li class="divider"></li>

                                    <li role="">
                                        <a class="btn-success" href="/performer/create" style="color: white;">
                                            <i class="icon-film"></i>
                                            Create Performer
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a id="band-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <i class="icon-cogs"></i>
                                    <?php echo $this->translate('Bands') ?>
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="band-drop" role="menu">

                                    <li role="menuitem">
                                        <form class="navbar-search pull-left" id="band-search" action="/band/search">
                                            <?= $this->inputBand(null, 'Search'); ?>
                                        </form>

                                        <script>
                                            $(function() {
                                                $('#band-search').on('submit', function(event) {
                                                    if ($(this).find('input[name="band_id"]').val()) {
                                                        window.location = '/band/detail?id='
                                                            + $(this).find('input[name="band_id"]').val();
                                                    }

                                                    return false;
                                                });
                                            });
                                        </script>
                                    </li>

                                    <?php
                                    if (isset($_SESSION['bands']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['bands']['latest'] as $id) {
                                            if ($p = $this->findEntity('Db\Entity\Band', $id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/band/detail?id=<?= $p->getId(); ?>">
                                                            <i class="icon-cogs"></i>
                                                            <?= $this->escapeHtml($p->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <?php
                                    if (isset($_SESSION['lineups']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['lineups']['latest'] as $id) {
                                            if ($p = $this->findEntity('Db\Entity\Lineup', $id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/lineup/detail?id=<?= $p->getId(); ?>">
                                                            <i class="icon-group"></i>
                                                            <?= $this->escapeHtml($p->getName()); ?>

                                                            <i class="icon-cogs"></i>
                                                            <?= $this->escapeHtml($p->getBand()->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <li class="divider"></li>

                                    <li role="">
                                        <a class="btn-success" href="/band/create" style="color: white;">
                                            <i class="icon-cogs"></i>
                                            Create Band
                                        </a>
                                    </li>


                                </ul>
                            </li>


                            <li class="dropdown">
                                <a id="venue-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <i class="icon-map-marker"></i>
                                    <?php echo $this->translate('Venues') ?>
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="venue-drop" role="menu">

                                    <li role="menuitem">
                                        <form class="navbar-search pull-left" id="venue-search" action="/venue/search">
                                            <?= $this->inputVenue(null, 'Search'); ?>
                                        </form>

                                        <script>
                                            $(function() {
                                                $('#venue-search').on('submit', function(event) {
                                                    if ($('form#venue-search input[name="venue_id"]').val()) {
                                                        window.location = '/venue/detail?id='
                                                            + $('form#venue-search [name="venue_id"]').val();
                                                    }

                                                    return false;
                                                });
                                            });
                                        </script>
                                    </li>

                                    <?php
                                    if (isset($_SESSION['venues']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['venues']['latest'] as $id) {
                                            if ($v = $this->findVenue($id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/venue/detail?id=<?= $v->getId(); ?>">
                                                            <i class="icon-map-marker"></i>
                                                            <?= $this->escapeHtml($v->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <li class="divider"></li>

                                    <li>
                                        <a class="btn btn-success" href="#" onClick="
                                            $('<span class=modal></span>').appendTo('body').load('/venue/create').modal();
                                            ">
                                            <i class="icon-map-marker"></i>
                                            Create Venue
                                        </a>
                                    </li>

                                </ul>
                            </li>


                            <li class="dropdown">
                                <a id="performance-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <i class="icon-magic"></i>
                                    <?php echo $this->translate('Performances') ?>
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="performance-drop" role="menu">

                                    <li role="menuitem">
                                        <form class="navbar-search pull-left" name="search" action="/performance/search">
                                            <input type="text" name="name" id="name" maxlength="85" size="28" autocomplete="off" placeholder="Search Performances">
                                        </form>
                                    </li>

                                    <?php
                                    if (isset($_SESSION['performances']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['performances']['latest'] as $id) {
                                            if ($p = $this->findEntity('Db\Entity\Performance', $id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/performance/detail?id=<?= $p->getId(); ?>">
                                                            <i class="icon-magic"></i>
                                                            <?php
                                                            if ($p->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
                                                                echo $this->escapeHtml($p->getPerformanceDateAt()->format('F d, Y'));
                                                            } else {
                                                                echo $this->escapeHtml($p->getPerformanceDate());
                                                            }
                                                            ?>

                                                            <?= $this->escapeHtml($p->getName()); ?>
                                                            <i class="icon-cogs"></i>
                                                            <?= $this->escapeHtml($p->getLineup()->getBand()->getName()); ?>

                                                            <i class="icon-map-marker"></i>
                                                            <?= $this->escapeHtml($p->getVenue()->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <li class="divider"></li>

                                    <li role="">
                                        <a class="btn-success" id="createPerformance" href="/performance/create" style="color: white;">
                                            <i class="icon-magic"></i>
                                            Create Performance
                                        </a>
                                    </li>

                                </ul>
                            </li>

                            <li class="dropdown">
                                <a id="performance-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <i class="icon-music"></i>
                                    <?php echo $this->translate('Songs') ?>
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="performance-drop" role="menu">

                                    <li role="menuitem">
                                        <form class="navbar-search pull-left" name="search" action="/performance/search">
                                            <input type="text" name="name" id="name" maxlength="85" size="28" autocomplete="off" placeholder="Search Songs">
                                        </form>
                                    </li>

                                    <?php
                                    if (isset($_SESSION['songs']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['songs']['latest'] as $id) {
                                            if ($p = $this->findEntity('Db\Entity\Song', $id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/song/detail?id=<?= $p->getId(); ?>">
                                                            <i class="icon-music"></i>
                                                            <?= $this->escapeHtml($p->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <li class="divider"></li>

                                    <li role="">
                                        <a class="btn-success" id="createSong" href="/song/create" style="color: white;">
                                            <i class="icon-music"></i>
                                            Create Song
                                        </a>
                                    </li>

                                </ul>
                            </li>



                            <li class="dropdown">
                                <a id="source-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <i class="icon-headphones"></i>
                                    <?php echo $this->translate('Sources') ?>
                                    <b class="caret"></b>
                                </a>

                                <ul class="dropdown-menu" aria-labelledby="source-drop" role="menu">

                                    <li role="menuitem">
                                        <form class="navbar-search pull-left" name="search" action="/source/search">
                                            <input type="text" name="name" id="name" maxlength="85" size="28" autocomplete="off" placeholder="Search Sources">
                                        </form>
                                    </li>

                                    <?php
                                    if (isset($_SESSION['sources']['latest'])) {
                                    ?><li class="divider"></li><?php
                                        foreach ($_SESSION['sources']['latest'] as $id) {
                                            if ($p = $this->findEntity('Db\Entity\Source', $id)) {
                                                ?>
                                                    <li role="menuitem">
                                                        <a href="/source/detail?id=<?= $p->getId(); ?>">
                                                            <i class="icon-headphones"></i>
                                                            <?= $this->escapeHtml($p->getName()); ?>

                                                            <i class="icon-magic"></i>
                                                            <?php
                                                            if ($p->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
                                                                echo $this->escapeHtml($p->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
                                                            } else {
                                                                echo $this->escapeHtml($p->getPerformance()->getPerformanceDate());
                                                            }
                                                            ?>

                                                            <i class="icon-cogs"></i>
                                                            <?= $this->escapeHtml($p->getPerformance()->getLineup()->getBand()->getName()); ?>

                                                            <i class="icon-map-marker"></i>
                                                            <?= $this->escapeHtml($p->getPerformance()->getVenue()->getName()); ?>
                                                        </a>
                                                    </li>
                                                <?php
                                            }
                                        }
                                    }
                                    ?>

                                    <li class="divider"></li>

                                    <li role="">
                                        <a class="btn-success" id="createSource" href="/performance/create" style="color: white;">
                                            <i class="icon-headphones"></i>
                                            Create Source
                                        </a>
                                    </li>

                                </ul>
                            </li>


                            <li>
                                <a href="/audit">
                                    <i class="icon-list"></i>
                                    Audit Log
                                </a>
                            </li>
                        </ul>
<!--
                            <form class="navbar-search pull-left" name="search">
                                <input type="text" name="name" id="name" maxlength="85" size="32" autocomplete="off" placeholder="band name">
                                <input type="text" name="date" id="date" maxlength="10" size="10" placeholder="show date">
                                <input type="submit" value="search">
                            </form>
-->
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 by db.etree.org <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>

        <script>

        require(['datemask', 'bootstrap.min'], function() {
            $('#date').datemask();

            $('#name').typeahead({
                source: function(query, process) {
                    return $.ajax({
                        url: '/db/artists/ajaxlookup',
                        type: 'get',
                        data: {query: query},
                        dataType: 'json',
                        success: function(json) {
                            return typeof json.options == 'undefined' ? false : process(json.options);
                        }
                    });
                },
                suppressKeyPressRepeat: true,
            });

            $('#createPerformance').click(function(event) {
                alert('To create a performance select a lineup from a band');
                return false;
            });

            $('#createSource').click(function(event) {
                alert('To create a source select a performance');
                return false;
            });
        });

        </script>

        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-37617360-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>

    </body>
</html>
