<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('db.etree.org')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/images/db-logo.png'))
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->appendFile($this->basePath() . '/scripts/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->setAllowArbitraryAttributes(true)
                                      ->prependFile($this->basePath() . '/scripts/require-jquery.js', 'text/javascript', array('data-main' => '/scripts/main')) ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><img src="/images/db-logo.png"></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <?php
                            if ($this->zfcUserIdentity()) {
                            ?>
                            <li id="user-menu" class="dropdown">
                                <a id="user-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 24)); ?>
                                    <?php echo $this->zfcUserDisplayName() ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="user-drop" role="menu">
                                    <li role="menuitem"><a href="/user/profile">Profile</a></li>
                                    <li role="menuitem"><i class="icon-signout"></i> <a href="/user/logout">Logout</a></li>
                                </ul>
                            </li>
                        <?php
                        } else {
                        ?>
                            <li><a href="/user/login">
                                <i class="icon-signin"></i>
                                Sign In
                            </a></li>
                        <?php
                        }
                        ?>
                        </ul>

                        <ul class="nav" id="menu">


                        </ul>

                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 by db.etree.org <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>

        <script>

        require(['datemask', 'bootstrap.min'], function() {
            $('#date').datemask();

            $('#name').typeahead({
                source: function(query, process) {
                    return $.ajax({
                        url: '/db/artists/ajaxlookup',
                        type: 'get',
                        data: {query: query},
                        dataType: 'json',
                        success: function(json) {
                            return typeof json.options == 'undefined' ? false : process(json.options);
                        }
                    });
                },
                suppressKeyPressRepeat: true,
            });

            $('#createPerformance').click(function(event) {
                alert('To create a performance select a lineup from a band');
                return false;
            });

            $('#createSource').click(function(event) {
                alert('To create a source select a performance');
                return false;
            });
        });

        </script>

        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-37617360-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>

    </body>
</html>
