<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->appendFile($this->basePath() . '/scripts/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->setAllowArbitraryAttributes(true)
                                      ->prependFile($this->basePath() . '/scripts/require-jquery.js', 'text/javascript', array('data-main' => '/scripts/main')) ?>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">db.etree.org</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <?php
                            if (isset($_SESSION['Zend_Auth']) and isset($_SESSION['Zend_Auth']['storage'])) {
                            ?>
                            <li id="user-menu" class="dropdown">
                                <a id="userdrop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 24)); ?>
                                    <?php echo $this->zfcUserDisplayName() ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userdrop" role="menu">
                                    <li role="menuitem"><a href="/user/profile">Profile</a></li>
                                    <li role="menuitem"><a href="/user/logout">Logout</a></li>
                                </ul>
                            </li>
                        <?php
                        } else {
                        ?>
                            <li><a href="/user/login">Login</a></li>
                        <?php
                        }
                        ?>
                        </ul>

                        <ul class="nav">
                            <li class=""><a href="/artist"><?php echo $this->translate('Artists') ?></a></li>
                            <li class=""><a href="/show"><?php echo $this->translate('Shows') ?></a></li>
                            <li class=""><a href="/source"><?php echo $this->translate('Sources') ?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 by db.etree.org <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>

        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-37617360-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>

    </body>
</html>
