<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-ok-circle"></i>
            Create Checksum
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('content')); ?>

        <?= $this->PasteUpload('content', 'Paste Uploaded File to Content'); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-success">
            <i class="icon-ok-circle"></i>
            Create Checksum
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {

    $('form#checksum').attr('id', 'checksum<?= $id; ?>');
    $('form#checksum<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '/checksum/create?id=<?= $source->getId(); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                $(this.span).modal('hide');
                if (data) $('<span class=modal></span>').appendTo('body').html(data).modal();
            }
        });

        return false;
    });
});

</script>