<a class="pull-right btn-warning" href="<?=
    $this->url('checksum/edit', array(
        'id' => $this->checksum->getId(),
    )); ?>">
    <i class="icon-map-marker"></i>
    Edit Checksum
</a>

<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->checksum)
);
?>

<h1>
    <i class="icon-ok-circle"></i>
    <?= $this->escapeHtml($this->checksum->getName()); ?>
</h1>

<h1>
    <a href="<?=
        $this->url('source/detail', array(
            'id' => $this->checksum->getSource()->getId(),
        )); ?>">
        <i class="icon-headphones"></i>
        <?= $this->escapeHtml($this->checksum->getSource()->getNote()); ?>
    </a>
</h1>


<h1>
    <a href="<?=
        $this->url('performance/detail', array(
            'id' => $this->checksum->getSource()->getPerformance()->getId(),
        )); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->checksum->getSource()->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->checksum->getSource()->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->checksum->getSource()->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->checksum->getSource()->getPerformance()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="<?=
        $this->url('band/detail', array(
            'id' => $this->checksum->getSource()->getPerformance()->getLineup()->getBand()->getId(),
        )); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->checksum->getSource()->getPerformance()->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="<?=
        $this->url('venue/detail', array(
            'id' =>  $this->checksum->getSource()->getPerformance()->getVenue()->getId(),
        )); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->checksum->getSource()->getPerformance()->getVenue()->getName()); ?>
    </a>
</h1>


<pre><?= $this->escapeHtml($this->checksum->getContent()); ?></pre>
