<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-ok-circle"></i>
            Edit Checksum
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('content')); ?>

        <?= $this->PasteUpload('content', 'Paste Uploaded File to Content'); ?>

        <?= $this->checksum->getName(); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-warning">
            <i class="icon-ok-circle"></i>
            Edit Checksum
        </button>

        <a class="btn btn-danger confirm" href="/checksum/delete?id=<?= $this->checksum->getId(); ?>">
            <i class="icon-ok-circle"></i>
            Delete Checksum
        </a>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('form#checksum').attr('id', 'checksum<?= $id; ?>');
    $('form#checksum<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '/checksum/edit?id=<?= $this->checksum->getId(); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});
</script>