<h1>
    <i class="icon-headphones"></i>
    Create Source
</h1>

<h1>
    <a href="/performance/detail?id=<?= $this->performance->getId(); ?>">
        <i class="icon-magic"></i>
    <?php
    if ($this->performance->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
        echo $this->escapeHtml($this->performance->getPerformanceDateAt()->format('F d, Y'));
    } else {
        echo $this->escapeHtml($this->performance->getPerformanceDate());
    }
    ?>

        <?= $this->escapeHtml($this->performance->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->performance->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->performance->getLineup()->getBand()->getName()); ?>
    </a>
</h1>


<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->formRow($this->form->get('format')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<?= $this->formRow($this->form->get('content')->setLabel('Textdoc')); ?>

<?= $this->pasteUpload('content', 'Paste Uploaded File to Textdoc'); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-headphones"></i>
    Create Source
</button>

<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('#lookup-zipcode').on('click', function(event) {
        $('#lookup-alert').hide();

        if ($('#country').val() && $('#zipcode').val()) {
            $.ajax({
                url: 'http://api.zippopotam.us/'
                    + $('#country').val().trim().toLowerCase()
                    + '/'
                    + $('#zipcode').val().trim().toLowerCase()
                    ,
                success: function(data) {
                    if (data.places.length == 1) {
                        $('#city').val(data.places[0]['place name']);
                        $('#state').val(data.places[0]['state abbreviation']);
                    } else {
                        alert('more than one place found');
                    }
                },
                dataType: 'json'
            });
        } else {
            $('#lookup-alert').show();
        }

        return false;
    });
});
</script>
