<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->source)
);
?>
<div class="h1">
    <a href="#" class="btn btn-warning edit-source" data-id="<?= $this->source->getId(); ?>">
        <i class="icon-headphones"></i>
    </a>

    <i class="icon-headphones"></i>
    <?= $this->escapeHtml($this->source->getName()); ?>
</div>

<div class="h1">
    <?= $this->escapeHtml($this->source->getFormat()); ?>
</div>

<pre><?= $this->escapeHtml($this->source->getNote()); ?></pre>


<div class="h1">
    <a class="btn btn-info" href="/performance/detail/<?= $this->source->getPerformance()->getId(); ?>">
        <i class="icon-magic"></i>
    </a>
<?php
if ($this->source->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->source->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->source->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->source->getPerformance()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-info" href="/band/detail/<?= $this->source->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
    </a>

    <?= $this->escapeHtml($this->source->getPerformance()->getLineup()->getBand()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-info" href="/venue/detail/<?= $this->source->getPerformance()->getVenue()->getId(); ?>">
        <i class="icon-map-marker"></i>
    </a>
    <?= $this->escapeHtml($this->source->getPerformance()->getVenue()->getName()); ?>
</div>

<div class="row">
    <div class="span12">
        <pre><?= $this->escapeHtml($this->source->getContent()); ?></pre>
    </div>
</div>


<div class="row">
    <div class="span3">
        <b>Name</b>
    </div>
    <div class="span3">
        <b>Media Size Compressed</b>
    </div>
    <div class="span3">
        <b>Media Size Uncompressed</b>
    </div>
    <div class="span3">
        <b>Circulated</b>
    </div>
</div>

<div class="row">
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getName()); ?>&nbsp;</pre>
    </div>
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getMediaSizeCompressed()); ?>&nbsp;</pre>
    </div>
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getMediaSizeUncompressed()); ?>&nbsp;</pre>
    </div>
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getCirculatedAt()); ?>&nbsp;</pre>
    </div>
</div>

<div class="h1">Checksums</div>

<a href="#" class="btn btn-success create-checksum" data-id="<?= $this->source->getId(); ?>">
    <i class="icon-ok-circle"></i>
</a>

<?php
foreach ($this->source->getChecksums() as $checksum) {
?>
    <div class="h2">
        <a class="btn btn-warning edit-checksum" href="#" data-id="<?= $checksum->getId(); ?>">
            <i class="icon-ok-circle"></i>
        </a>

        <?= $this->escapeHtml($checksum->getName()); ?>

        <pre><?= $this->escapeHtml($checksum->getContent()); ?></pre>
    </div>


<?php
}
?>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>
</ul>

<div class="tab-content">
   <div class="tab-pane active" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->source->getId(), 'Db\Entity\Source', '/source/detail/' . $this->source->getId()); ?>
        </ul>

        <?= $this->listComments($this->source->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <?= $this->createLink($this->source->getId(), 'Db\Entity\Source', '/source/detail/' . $this->source->getId()); ?>

        <?= $this->listLinks($this->source->getLinks()); ?>
    </div>
</div>
