<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-warning" href="/source/edit?id=<?= $this->source->getId(); ?>">
            <i class="icon-map-marker"></i>
            Edit Source
        </a>
    </li>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->source->getId(); ?>/Db\Entity\Source">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<h1>
    <i class="icon-headphones"></i>
    <?= $this->escapeHtml($this->source->getNote()); ?>
</h1>

<h1>
    <?= $this->escapeHtml($this->source->getFormat()); ?>
</h1>

<h1>
    <a href="/performance/detail?id=<?= $this->source->getPerformance()->getId(); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->source->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->source->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->source->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->source->getPerformance()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->source->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->source->getPerformance()->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/venue/detail?id=<?= $this->source->getPerformance()->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->source->getPerformance()->getVenue()->getName()); ?>
    </a>
</h1>

<div class="row">
    <div class="span12">
        <pre><?= $this->escapeHtml($this->source->getContent()); ?></pre>
    </div>
</div>


<div class="row">
    <div class="span3">
        <b>Name</b>
    </div>
    <div class="span3">
        <b>Media Size Compressed</b>
    </div>
    <div class="span3">
        <b>Media Size Uncompressed</b>
    </div>
    <div class="span3">
        <b>Circulated</b>
    </div>
</div>

<div class="row">
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getName()); ?>&nbsp;</pre>
    </div>
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getMediaSizeCompressed()); ?>&nbsp;</pre>
    </div>
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getMediaSizeUncompressed()); ?>&nbsp;</pre>
    </div>
    <div class="span3">
        <pre><?= $this->escapeHtml($this->source->getCirculatedAt()); ?>&nbsp;</pre>
    </div>
</div>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>
</ul>

<div class="tab-content">
   <div class="tab-pane active" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->source->getId(), 'Db\Entity\Source', '/source/detail?id=' . $this->source->getId()); ?>
        </ul>

        <?= $this->listComments($this->source->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <ul class="nav nav-pills">
            <?= $this->createLink($this->source->getId(), 'Db\Entity\Source', '/source/detail?id=' . $this->source->getId()); ?>
        </ul>
    </div>
</div>
