<h1>
    <i class="icon-map-marker"></i>
    Edit Venue
</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('country')); ?>

<?= $this->formRow($this->form->get('zipcode')); ?>

<a href="#" id="lookup-zipcode" class="btn btn-primary"><i class="icon-book"></i> Lookup</a>
<div class="alert" style="display: none;" id="lookup-alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    Enter Country and Zipcode to Lookup location
</div>

<?= $this->formRow($this->form->get('city')); ?>

<?= $this->formRow($this->form->get('state')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-map-marker"></i>
    Edit Venue
</button>

<a class="btn btn-link" href="/venue/detail?id=<?= $this->venue->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('#lookup-zipcode').on('click', function(event) {
        $('#lookup-alert').hide();

        if ($('#country').val() && $('#zipcode').val()) {
            $.ajax({
                url: 'http://api.zippopotam.us/'
                    + $('#country').val().trim().toLowerCase()
                    + '/'
                    + $('#zipcode').val().trim().toLowerCase()
                    ,
                success: function(data) {
                    if (data.places.length == 1) {
                        $('#city').val(data.places[0]['place name']);
                        $('#state').val(data.places[0]['state abbreviation']);
                    } else {
                        alert('more than one place found');
                    }
                },
                dataType: 'json'
            });
        } else {
            $('#lookup-alert').show();
        }

        return false;
    });
});
</script>
