<h1>
    <i class="icon-headphones"></i>
    Edit Source
</h1>

<h1>
    <a href="/performance/detail?id=<?= $this->source->getPerformance()->getId(); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->source->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->source->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->source->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->source->getPerformance()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->source->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->source->getPerformance()->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/venue/detail?id=<?= $this->source->getPerformance()->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->source->getPerformance()->getVenue()->getName()); ?>
    </a>
</h1>



<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->formRow($this->form->get('format')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<?= $this->formRow($this->form->get('content')->setLabel('Textdoc')); ?>

<?= $this->pasteUpload('content', 'Paste Uploaded File to Textdoc'); ?>

<?= $this->formRow($this->form->get('mediaSizeCompressed')); ?>

<?= $this->formRow($this->form->get('mediaSizeUncompressed')); ?>

<?= $this->formRow($this->form->get('circulatedAt')); ?>


<br>

<button type="send" class="btn btn-warning">
    <i class="icon-headphones"></i>
    Edit Source
</button>

<a class="btn btn-link" href="/source/detail?id=<?= $this->source->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>
