<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-headphones"></i>
            Edit Source
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('mbid')); ?>

        <?= $this->formRow($this->form->get('format')); ?>

        <?= $this->formRow($this->form->get('note')); ?>

        <?= $this->formRow($this->form->get('content')->setLabel('Textdoc')); ?>

        <?= $this->pasteUpload('content', 'Paste Uploaded File to Textdoc'); ?>

        <?= $this->formRow($this->form->get('mediaSizeCompressed')); ?>

        <?= $this->formRow($this->form->get('mediaSizeUncompressed')); ?>

        <?= $this->formRow($this->form->get('circulatedAt')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-warning">
            <i class="icon-headphones"></i>
            Edit Source
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('form#source').attr('id', 'source<?= $id; ?>');
    $('form#source<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '/source/edit?id=<?= $this->source->getId(); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});
</script>