<a class="pull-right btn-warning" href="<?=
    $this->url('performance-song/edit', array(
        'id' => $this->performanceSong->getId(),
    )); ?>">
    <i class="icon-music"></i>
    Edit Performance Set Song
</a>

<a class="pull-right btn-danger confirm" href="<?=
    $this->url('performance-song/delete', array(
        'id' => $this->performanceSong->getId(),
    )); ?>">
    <i class="icon-music"></i>
    Delete Performance Set Song
</a>

<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->performanceSong)
);
?>

<h1>
    <a href="<?=
        $this->url('performance/detail', array(
            'id' => $this->performanceSong->getPerformanceSet()->getPerformance()->getId(),
        )); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->performanceSong->getPerformanceSet()->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performanceSong->getPerformanceSet()->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performanceSong->getPerformanceSet()->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performanceSong->getPerformanceSet()->getPerformance()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="<?=
        $this->url('band/detail', array(
            'id' => $this->performanceSong->getPerformanceSet()->getPerformance()->getLineup()->getBand()->getId(),
        )); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->performanceSong->getPerformanceSet()->getPerformance()->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="<?=
        $this->url('lineup/detail', array(
            'id' => $this->performanceSong->getPerformanceSet()->getPerformance()->getLineup()->getBand()->getId(),
        )); ?>">
        <i class="icon-group"></i>
        <?= $this->escapeHtml($this->performanceSong->getPerformanceSet()->getPerformance()->getLineup()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="<?=
        $this->url('venue/detail', array(
            'id' => $this->performanceSong->getPerformanceSet()->getPerformance()->getVenue()->getId(),
        )); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->performanceSong->getPerformanceSet()->getPerformance()->getVenue()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="<?=
        $this->url('performance-set/detail', array(
            'id' => $this->performanceSong->getPerformanceSet()->getId(),
        )); ?>">
        <i class="icon-certificate"></i>
        <?= $this->escapeHtml($this->performanceSong->getPerformanceSet()->getName()); ?>
    </a>
</h1>


<h1>
    <a href="<?=
        $this->url('song/detail', array(
            'id' => $this->performanceSong->getSong()->getId(),
        )); ?>">
        <i class="icon-music"></i>
        <?= $this->escapeHtml($performanceSong->getSong()->getName()); ?></a><?php if ($performanceSong->getIsSegue()) echo ' &gt; '; ?></pre>
    </a>
</h1>

<?php
if ($this->performanceSong->getLength()) {
?>
    <pre><?= $this->escapeHtml($this->performanceSong->getLength()); ?></pre>
<?php
}
?>

<?php
if ($this->performanceSong->getNote()) {
?>
    <pre><?= $this->escapeHtml($this->performanceSong->getNote()); ?></pre>
<?php
}
?>
