<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-bolt"></i>
            Edit Performance Set Song
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->inputSong($this->performanceSetSong->getSong()); ?>

        <?= $this->formRow($this->form->get('length')); ?>

        <?= $this->formRow($this->form->get('note')); ?>

        <?= $this->formRow($this->form->get('isSegue')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-warning">
            <i class="icon-bolt"></i>
            Edit Performance Set Song
        </button>

        <a href="/performance-set-song/delete?id=<?= $this->id; ?>" class="btn btn-danger confirm">
            <icon class="icon-bolt"></i>
            Delete Performance Set Song
        </a>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('form#performance-set-song').attr('id', 'performance-set-song<?= $id; ?>');
    $('form#performance-set-song<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '/performance-set-song/edit?id=<?= $this->id; ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});
</script>
