<ul class="nav nav-pills pull-right">
    <li class="">
        <a href="/country">Back to Countries</a>
    </li>
</ul>

<h1>Places</h1>
<h2>
    <?= $this->escapeHtml($this->state->getCountry()->getName()); ?>
    &gt;
    <?= $this->escapeHtml($this->state->getName()); ?>
</h2>

<hr>

<?php

$col1 = $col2 = $col3 = array();
$i = 0;
foreach ($this->places as $entity) {
    $i ++;
    switch ($i) {
        case 1:
            $col1[] = $entity;
            break;
        case 2:
            $col2[] = $entity;
            break;
        case 3:
        default:
            $i = 0;
            $col3[] = $entity;
            break;
    }
}

?>


<div class="row">
    <div class="span4">
        <?php
        foreach ($col1 as $entity) {
        ?>
            <h5>
                <a href="/place?stateId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col2 as $entity) {
        ?>
            <h5>
                <a href="/place?stateId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col3 as $entity) {
        ?>
            <h5>
                <a href="/place?stateId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
</div>
