<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-facetime-video"></i>
            Create Band Alias
        </h1>
    </div>

    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('note')); ?>

    </div>

    <div class="modal-footer">
        <button type="send" class="btn btn-success">
            <i class="icon-facetime-video"></i>
            Create Band Alias
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>
    </div>

<?= $this->form()->closeTag(); ?>


<script>
$(function() {

    $('form#band-alias').attr('id', 'band-alias<?= $id; ?>');
    $('form#band-alias<?= $id; ?>').on('submit', function(event) {

        $.ajax({
            url: '/band-alias/create/<?= $this->band->getId(); ?>',

            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {

                    $(this.span).modal('hide');
                    //Menu.refresh();
                    window.location.reload();
                }
            }
        });

        return false;
    });
});

</script>