<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->bandAlias)
);
?>

<div class="h1">
    <a class="btn btn-warning" href="#" data-id="<?= $this->bandAlias->getId(); ?>">
        <i class="icon-legal"></i>
    </a>
    <i class="icon-legal"></i>
    <?= $this->escapeHtml($this->bandAlias->getName()); ?>
</div>

<div class="h1">

    <a class="btn btn-info" href="/band/detail?id=<?= $this->bandAlias->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
    </a>

    <?= $this->escapeHtml($this->bandAlias->getBand()->getName()); ?>
</div>


<?php
if ($this->escapeHtml($this->bandAlias->getNote())) {
?>
    <pre><?= $this->escapeHtml($this->bandAlias->getNote()); ?></pre>
<?php
}
?>
