<ul class="nav nav-pills pull-right">
    <li>
        <a data-id="<?= $this->bandAlias->getId(); ?>" class="btn-warning edit-band-alias" href="#">
            <i class="icon-user"></i>
            Edit Band Alias
        </a>
    </li>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->bandAlias->getId(); ?>/Db\Entity\bandAlias">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>


<div class="h1">

    <a class="btn btn-info" href="/band/detail?id=<?= $this->bandAlias->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
    </a>

    <?= $this->escapeHtml($this->bandAlias->getBand()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-default" href="/band-alias/detail?id=<?= $this->bandAlias->getId(); ?>">
        <i class="icon-facetime-video"></i>
    </a>
    <?= $this->escapeHtml($this->bandAlias->getName()); ?>
</div>

<?php
if ($this->escapeHtml($this->bandAlias->getNote())) {
?>
    <pre><?= $this->escapeHtml($this->bandAlias->getNote()); ?></pre>
<?php
}
?>
