<ul class="nav nav-pills pull-right">

    <li class="">
        <a class="btn-warning" href="/performer/edit?id=<?= $this->performer->getId(); ?>"><i class="icon-film"></i> Edit Performer</a>
    </li>

    <?php
    if (!sizeof($this->performer->getAliases())
        and !sizeof($this->performer->getLineups())
        and !sizeof($this->performer->getPerformances())
        and !sizeof($this->performer->getLinks())
        and !sizeof($this->performer->getComments()))
    {
    ?>
        <li class="">
            <a class="btn-danger confirm" href="/performer/delete?id=<?= $this->performer->getId(); ?>"><i class="icon-film"></i> Delete Performer</a>
        </li>
    <?php
    }
    ?>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->performer->getId(); ?>/Db\Entity\Performer">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<h1>
    <i class="icon-film"></i>
    <?= $this->escapeHtml($this->performer->getName()); ?>

    <?php
    if ($this->performer->getNote()) {
    ?>
    <pre><?= $this->escapeHtml($this->performer->getNote()); ?></pre>
    <?php
    }
    ?>
</h1>

<?php
use Gracenote\Service\Gracenote;

$gracenote = Gracenote::query('ALBUM_SEARCH', array(
    'parameters' => array(
        'ARTIST' => $this->performer->getName(),
    ),
    'options' => array(
        'SELECT_EXTENDED' => 'COVER',
    ),
));

use \Echonest\Service\Echonest;

$echonest = Echonest::query('artist', 'biographies', array(
    'name' => $this->performer->getName(),
    'results' => '1',
    'start' => '0',
));

?>

<ul class="nav nav-tabs" id="tabs">
        <?php
            if ($echonest->response->status->message == 'Success') {
            ?>
                <li class="active">
                    <a href="#biography" data-toggle="tab">
                        Biography
                    </a>
                </li>
            <?php
            }
        ?>

<?php
if (sizeof($gracenote->RESPONSE->ALBUM)) {
?>
    <li class="">
        <a href="#gracenote-albums" data-toggle="tab">
            Albums
        </a>
    </li>
<?php
}
?>

    <li class="">
        <a href="#performances" data-toggle="tab">
            Performances
        </a>
    </li>

    <li class="">
        <a href="#aliases" data-toggle="tab">
            Aliases
        </a>
    </li>

    <li class="">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>


</ul>

<div class="tab-content">

    <div class="tab-pane active" id="biography">
        <ul class="nav nav-pills">
            <?php
                if ($echonest->response->status->message == 'Success') {
                    foreach ($echonest->response->biographies as $bio) {
                ?>
                    <pre><?= $this->escapeHtml($bio->text); ?></pre>

                <?php
                    }
                }
                ?>
        </ul>
    </div>

    <div class="tab-pane" id="performances">
        <ul class="nav nav-pills">
            <?= $this->listPerformances($this->performer->getPerformances()); ?>
        </ul>
    </div>

    <?
    if (sizeof($gracenote->RESPONSE->ALBUM)) {
    ?>
    <div class="tab-pane" id="gracenote-albums">
        <div class="row">
            <div class="span1">
                <b>Date</b>
            </div>

            <div class="span4">
                <b>Artist</b>
            </div>

            <div class="span6">
                <b>Title</b>
            </div>
        </div>

        <?php
            foreach ($gracenote->RESPONSE->ALBUM as $album) {
        ?>
            <div class="row">
                <div class="span1">
                    <pre><?= $this->escapeHtml((string)$album->DATE); ?>&nbsp;</pre>
                </div>
                <div class="span4">
                    <pre><?= $this->escapeHtml((string)$album->ARTIST); ?>&nbsp;</pre>
                </div>
                <div class="span6">
                    <pre><?= $this->escapeHtml((string)$album->TITLE); ?></pre>
                </div>
            </div>

        <?php
            }
        }
        ?>
    </div>

    <div class="tab-pane" id="aliases">
        <?php
        foreach ($this->performer->getAliases() as $alias) {
        ?>
            <i class="icon-facetime-video"></i>
            <a href="/performer-alias/detail?id=<?= $alias->getId(); ?>">
                <?= $this->escapeHtml($alias->getName()); ?>
            </a>
            <br>
        <?php
        }
        ?>

        <ul class="nav nav-pills">
            <a href="#" data-id="<?= $this->performer->getId(); ?>" class="btn btn-success create-performer-alias">Create Performer Alias</a>
        </ul>

    </div>

   <div class="tab-pane" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->performer->getId(), 'Db\Entity\Performer', '/performer/detail?id=' . $this->performer->getId()); ?>
        </ul>

        <?= $this->listComments($this->performer->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <ul class="nav nav-pills">
            <?= $this->createLink($this->performer->getId(), 'Db\Entity\Performer', '/performer/detail?id=' . $this->performer->getId()); ?>
        </ul>
    </div>

</div>

