<ul class="nav nav-pills pull-right">

    <li class="">
        <a class="btn-warning" href="/performer/edit?id=<?= $this->performer->getId(); ?>"><i class="icon-film"></i> Edit Performer</a>
    </li>

    <?php
    if (!sizeof($this->performer->getAliases())
        and !sizeof($this->performer->getLineups())
        and !sizeof($this->performer->getPerformances())
        and !sizeof($this->performer->getLinks())
        and !sizeof($this->performer->getComments()))
    {
    ?>
        <li class="">
            <a class="btn-danger confirm" href="/performer/delete?id=<?= $this->performer->getId(); ?>"><i class="icon-film"></i> Delete Performer</a>
        </li>
    <?php
    }
    ?>
</ul>

<h1>
<i class="icon-film"></i>
<?= $this->escapeHtml($this->performer->getLastname()); ?>
<?php if ($this->escapeHtml($this->performer->getLastname())) echo ', '; ?>
<?= $this->escapeHtml($this->performer->getFirstname()); ?>
</h1>

<?php
if ($this->performer->getNote()) {
?>
<pre><?= $this->escapeHtml($this->performer->getNote()); ?></pre>
<?php
}
?>

<h3>Aliases</h3>
<ul>
<?php
foreach ($this->performer->getAliases() as $alias) {
?>
    <li>
        <a href="/performerAlias/detail?id=<?= $alias->getId(); ?>">
            <?= $this->escapeHtml($alias->getName()); ?>
        </a>
    </li>
<?php
}
?>
</ul>

<?php
use Gracenote\Service\Gracenote;

$gracenote = Gracenote::query('ALBUM_SEARCH', array(
    'parameters' => array(
        'ARTIST' => $this->performer->getFullname(),
    ),
    'options' => array(
        'SELECT_EXTENDED' => 'COVER',
    ),
));

?>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>

<?php
if (sizeof($gracenote->RESPONSE->ALBUM)) {
?>
    <li class="">
        <a href="#gracenote-albums" data-toggle="tab">
            Gracenote Albums
        </a>
    </li>
<?php
}
?>

</ul>

<div class="tab-content">

   <div class="tab-pane active" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->performer->getId(), 'Db\Entity\Performer', '/performer/detail?id=' . $this->performer->getId()); ?>
        </ul>

        <?= $this->listComments($this->performer->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <ul class="nav nav-pills">
            <?= $this->createLink($this->performer->getId(), 'Db\Entity\Performer', '/performer/detail?id=' . $this->performer->getId()); ?>
        </ul>
    </div>

    <?
    if (sizeof($gracenote->RESPONSE->ALBUM)) {
    ?>
    <div class="tab-pane" id="gracenote-albums">
        <div class="row">
            <div class="span1">
                <b>Date</b>
            </div>

            <div class="span4">
                <b>Artist</b>
            </div>

            <div class="span6">
                <b>Title</b>
            </div>
        </div>

        <?php
            foreach ($gracenote->RESPONSE->ALBUM as $album) {
        ?>
            <div class="row">
                <div class="span1">
                    <pre><?= $this->escapeHtml((string)$album->DATE); ?>&nbsp;</pre>
                </div>
                <div class="span4">
                    <pre><?= $this->escapeHtml((string)$album->ARTIST); ?>&nbsp;</pre>
                </div>
                <div class="span6">
                    <pre><?= $this->escapeHtml((string)$album->TITLE); ?></pre>
                </div>
            </div>

        <?php
            }
        }
        ?>
</div>

