<h1>Edit Performer</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('lastname')); ?>

<?= $this->formRow($this->form->get('firstname')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-film"></i>
    Edit Performer
</button>

<a class="btn btn-link" href="/performer/detail?id=<?= $this->performer->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>

<ul class="nav nav-pills">
    <?= $this->createPerformerAlias($this->performer->getId(), 'Db\Entity\Performer', '/performer/detail?id=' . $this->performer->getId()); ?>
</ul>
