<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-map-marker"></i>
            Create Venue
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('country')); ?>

        <?= $this->formRow($this->form->get('zipcode')->setAttribute('taborder', '30')); ?>

        <a href="#" id="lookup-zipcode<?= $id; ?>" class="btn btn-primary"><i class="icon-book"></i> Lookup</a>
        <div class="alert" style="display: none;" id="lookup-alert<?= $id; ?>">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Enter Country and Zipcode to Lookup location
        </div>

        <?= $this->formRow($this->form->get('city')); ?>

        <?= $this->formRow($this->form->get('state')); ?>

        <?= $this->formRow($this->form->get('note')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-success">
            <i class="icon-map-marker"></i>
            Create Venue
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {

    $('form#venue').attr('id', 'venue<?= $id; ?>');
    $('form#venue<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '/venue/create',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                $(this.span).modal('hide');
                if (data) $('<span class=modal></span>').appendTo('body').html(data).modal();
            }
        });

        return false;
    });

    $('#lookup-zipcode<?= $id; ?>').on('click', function(event) {
        $('#lookup-alert<?= $id; ?>').hide();

        if ($('#country').val() && $('#zipcode').val()) {
            $.ajax({
                url: 'http://api.zippopotam.us/'
                    + $('[name="country"]').val().trim().toLowerCase()
                    + '/'
                    + $('[name="zipcode"]').val().trim().toLowerCase()
                    ,
                success: function(data) {
                    if (data.places.length == 1) {
                        $('[name="city"]').val(data.places[0]['place name']);
                        $('[name="state"]').val(data.places[0]['state abbreviation']);
                    } else {
                        alert('more than one place found');
                    }
                },
                dataType: 'json'
            });
        } else {
            $('#lookup-alert<?= $id; ?>').show();
        }

        return false;
    });
});
</script>
