<h1>
    <i class="icon-map-marker"></i>
    Create Venue
</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?php
    //$this->formRow($this->form->get('place'));
?>

<?= $this->formRow($this->form->get('city')); ?>

<?= $this->formRow($this->form->get('state')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-map-marker"></i>
    Create Venue
</button>

<?= $this->form()->closeTag(); ?>
