<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-warning" href="/venue/edit?id=<?= $this->venue->getId(); ?>"><i class="icon-home"></i> Edit Venue</a>
    </li>

    <?php
    if (!sizeof($this->venue->getPerformances())
        and !sizeof($this->venue->getLinks())
        and !sizeof($this->venue->getComments())
        and !sizeof($this->venue->getVenueGroups()))
    {
    ?>
        <li class="">
            <a class="btn-danger confirm" href="/venue/delete?id=<?= $this->venue->getId(); ?>"><i class="icon-home"></i> Delete Venue</a>
        </li>
    <?php
    }
    ?>
</ul>

<h1>Venue</h1>
<h2><?= $this->escapeHtml($this->venue->getName()); ?></h2>

City: <?= $this->escapeHtml($this->venue->getCity()); ?>
<br>
State: <?= $this->escapeHtml($this->venue->getState()); ?>
<br>
Note: <?= $this->escapeHtml($this->venue->getNote()); ?>

<ul class="nav nav-pills">
    <?= $this->createLink($this->venue->getId(), 'Db\Entity\Venue', '/venue/detail?id=' . $this->venue->getId()); ?>

    <?= $this->createComment($this->venue->getId(), 'Db\Entity\Venue', '/venue/detail?id=' . $this->venue->getId()); ?>
</ul>


<?= $this->listComments($this->venue->getComments());
