<h1>
    <i class="icon-map-marker"></i>
    Edit Venue
</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?php
    //$this->formRow($this->form->get('place'));
?>

<?= $this->formRow($this->form->get('city')); ?>

<?= $this->formRow($this->form->get('state')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-map-marker"></i>
    Edit Venue
</button>

<a class="btn btn-link" href="/venue/detail?id=<?= $this->venue->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>
