<div class="h1">
    <i class="icon-map-marker"></i>
    Venues
</div>

<div class="row">
    <?php

    foreach ($venues as $index => $venue) {
    ?>
        <div class="span3" style="padding-top: 4px;">
            <a class="btn btn-info" href="/venue/detail?id=<?= $venue->getId(); ?>">
                <i class="icon-map-marker"></i>
            </a>

            <?= $this->escapeHtml($venue->getName()); ?>
        </div>
    <?php
    }
    ?>
</div>