<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-warning" href="/band/edit?id=<?= $this->band->getId(); ?>"><i class="icon-cogs"></i> Edit Band</a>
    </li>
</ul>

<h1><i class="icon-cogs"></i> <?= $this->escapeHtml($this->band->getName()); ?></h1>

<?php
if ($this->band->getNote()) {
?>
<pre><?= $this->escapeHtml($this->band->getNote()); ?></pre>
<?php
}
?>

<h3>
<?php
foreach ($this->band->getLineups() as $lineup) {
?>
    <i class="icon-group"></i>
    <a href="/lineup/detail?id=<?= $lineup->getId(); ?>">
        <?= $this->escapeHtml($lineup->getName()); ?>
    </a>
<?php
}
?>
</h3>

<?php
use Gracenote\Service\Gracenote;
use Jambase\Service\Jambase;

$gracenote = Gracenote::query('ALBUM_SEARCH', array(
    'parameters' => array(
        'ARTIST' => $this->band->getName(),
    ),
    'options' => array(
        'SELECT_EXTENDED' => 'COVER',
    ),
));

$jambase = Jambase::search(array('band' => $this->band->getName()));

use \Echonest\Service\Echonest;

$echonest = Echonest::query('artist', 'biographies', array(
    'name' => $this->band->getName(),
    'results' => '1',
    'start' => '0',
));

?>

<ul class="nav nav-tabs" id="tabs">
    <?php
        if ($echonest->response->status->message == 'Success') {
        ?>
            <li class="active">
                <a href="#biography" data-toggle="tab">
                    Biography
                </a>
            </li>
        <?php
        }
    ?>

<?php
if (sizeof($gracenote->RESPONSE->ALBUM)) {
?>
    <li class="">
        <a href="#albums" data-toggle="tab">
            Albums
        </a>
    </li>
<?php
}
?>

<?php
if (sizeof($jambase->event)) {
?>
    <li class="">
        <a href="#jambase" data-toggle="tab">
            Upcoming Shows
        </a>
    </li>
<?php
}
?>

    <li class="">
        <a href="#performances" data-toggle="tab">
            Performances
        </a>
    </li>

    <li class="">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>


</ul>

<div class="tab-content">
    <?php
        if ($echonest->response->status->message == 'Success') {
        ?>

    <div class="tab-pane active" id="biography">
        <ul class="nav nav-pills">
            <?php
                if ($echonest->response->status->message == 'Success') {
                    foreach ($echonest->response->biographies as $bio) {
                ?>
                    <pre><?= $this->escapeHtml($bio->text); ?></pre>

                <?php
                    }
                }
                ?>
        </ul>
    </div>

    <?php
    }
    ?>

<?php
if (sizeof($jambase->event)) {
?>
    <div class="tab-pane" id="jambase">
        <div class="row">
            <div class="span2">
                <b>Date</b>
            </div>

            <div class="span5">
                <b>Venue</b>
            </div>
            <div class="span3">
                <b>City</b>
            </div>
            <div class="span1">
                <b>State</b>
            </div>
        </div>

        <?php
        foreach ($jambase->event as $event) {
        ?>
            <div class="row">
                <div class="span2">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->event_date); ?></a></pre>
                </div>
                <div class="span5">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->venue->venue_name); ?></a></pre>
                </div>
                <div class="span3">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->venue->venue_city); ?></a></pre>
                </div>
                <div class="span1">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->venue->venue_state); ?></a></pre>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
<?php
}
?>

    <?
    if (sizeof($gracenote->RESPONSE->ALBUM)) {
    ?>
    <div class="tab-pane" id="albums">
        <div class="row">
            <div class="span1">
                <b>Date</b>
            </div>

            <div class="span4">
                <b>Artist</b>
            </div>

            <div class="span6">
                <b>Title</b>
            </div>
        </div>

        <?php
            foreach ($gracenote->RESPONSE->ALBUM as $album) {
        ?>
            <div class="row">
                <div class="span1">
                    <pre><?= $this->escapeHtml((string)$album->DATE); ?>&nbsp;</pre>
                </div>
                <div class="span4">
                    <pre><?= $this->escapeHtml((string)$album->ARTIST); ?>&nbsp;</pre>
                </div>
                <div class="span6">
                    <pre><?= $this->escapeHtml((string)$album->TITLE); ?></pre>
                </div>
            </div>

        <?php
            }
        }
        ?>
    </div>

   <div class="tab-pane" id="performances">
        <?= $this->listPerformances($this->band->getPerformances()); ?>
    </div>

   <div class="tab-pane" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->band->getId(), 'Db\Entity\Band', '/band/detail?id=' . $this->band->getId()); ?>
        </ul>

        <?= $this->listComments($this->band->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <ul class="nav nav-pills">
            <?= $this->createLink($this->band->getId(), 'Db\Entity\Band', '/band/detail?id=' . $this->band->getId()); ?>
        </ul>
    </div>

</div>