<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-warning" href="/band/edit?id=<?= $this->band->getId(); ?>"><i class="icon-cogs"></i> Edit Band</a>
    </li>
</ul>

<h1><i class="icon-cogs"></i> <?= $this->escapeHtml($this->band->getName()); ?></h1>

<?php
if ($this->band->getNote()) {
?>
<pre><?= $this->escapeHtml($this->band->getNote()); ?></pre>
<?php
}
?>

<ul>
<?php
foreach ($this->band->getLineups() as $lineup) {
?>
    <li>
        <i class="icon-group"></i>
        <a href="/lineup/detail?id=<?= $lineup->getId(); ?>">
            <?= $this->escapeHtml($lineup->getName()); ?>
        </a>
    </li>
<?php
}
?>
</ul>

<?php
use Gracenote\Service\Gracenote;
use Jambase\Service\Jambase;

$gracenote = Gracenote::query('ALBUM_SEARCH', array(
    'parameters' => array(
        'ARTIST' => $this->band->getName(),
    ),
    'options' => array(
        'SELECT_EXTENDED' => 'COVER',
    ),
));

$jambase = Jambase::search(array('band' => $this->band->getName()));

?>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>

<?php
if (sizeof($jambase->event)) {
?>
    <li class="">
        <a href="#jambase" data-toggle="tab">
            Jambase Shows
        </a>
    </li>
<?php
}
?>

<?php
if (sizeof($gracenote->RESPONSE->ALBUM)) {
?>
    <li class="">
        <a href="#gracenote-albums" data-toggle="tab">
            Gracenote Albums
        </a>
    </li>
<?php
}
?>
</ul>

<div class="tab-content">
   <div class="tab-pane active" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->band->getId(), 'Db\Entity\Band', '/band/detail?id=' . $this->band->getId()); ?>
        </ul>

        <?= $this->listComments($this->band->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <ul class="nav nav-pills">
            <?= $this->createLink($this->band->getId(), 'Db\Entity\Band', '/band/detail?id=' . $this->band->getId()); ?>
        </ul>
    </div>

<?php
if (sizeof($jambase->event)) {
?>
    <div class="tab-pane" id="jambase">
        <div class="row">
            <div class="span2">
                <b>Date</b>
            </div>

            <div class="span5">
                <b>Venue</b>
            </div>
            <div class="span3">
                <b>City</b>
            </div>
            <div class="span1">
                <b>State</b>
            </div>
        </div>

        <?php
        foreach ($jambase->event as $event) {
        ?>
            <div class="row">
                <div class="span2">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->event_date); ?></a></pre>
                </div>
                <div class="span5">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->venue->venue_name); ?></a></pre>
                </div>
                <div class="span3">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->venue->venue_city); ?></a></pre>
                </div>
                <div class="span1">
                    <pre><a href="<?= (string)$event->event_url; ?>"><?= $this->escapeHtml((string)$event->venue->venue_state); ?></a></pre>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
<?php
}
?>

    <?
    if (sizeof($gracenote->RESPONSE->ALBUM)) {
    ?>
    <div class="tab-pane" id="gracenote-albums">
        <div class="row">
            <div class="span1">
                <b>Date</b>
            </div>

            <div class="span4">
                <b>Artist</b>
            </div>

            <div class="span6">
                <b>Title</b>
            </div>
        </div>

        <?php
            foreach ($gracenote->RESPONSE->ALBUM as $album) {
        ?>
            <div class="row">
                <div class="span1">
                    <pre><?= $this->escapeHtml((string)$album->DATE); ?>&nbsp;</pre>
                </div>
                <div class="span4">
                    <pre><?= $this->escapeHtml((string)$album->ARTIST); ?>&nbsp;</pre>
                </div>
                <div class="span6">
                    <pre><?= $this->escapeHtml((string)$album->TITLE); ?></pre>
                </div>
            </div>

        <?php
            }
        }
        ?>
    </div>
</div>