<h1>Edit Band</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-cogs"></i>
    Edit Band
</button>

<a class="btn btn-link" href="/band/detail?id=<?= $this->band->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>

<ul class="nav nav-pills">
    <li class="">
         <a class="btn-success" href="/lineup/create?id=<?= $this->band->getId(); ?>">
            <i class="icon-group"></i>
            Create Lineup
        </a>
     </li>
</ul>