<h1>Edit Band</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-cogs"></i>
    Edit Band
</button>

<a class="btn btn-link" href="/band/detail?id=<?= $this->band->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>