<div class="h1">
    <i class="icon-magic"></i>
    Create Performance

<div class="h2">
    <a href="<?=
        $this->url('band/detail', array(
            'id' => $this->lineup->getBand()->getId(),
        )); ?>" class="btn btn-info">
        <i class="icon-cogs"></i>
    </a>

    <?= $this->escapeHtml($this->lineup->getBand()->getName()); ?>
</div>

<div class="h2">
    <a href="<?=
        $this->url('lineup/detail', array(
            'id' => $this->lineup->getId(),
        )); ?>" class="btn btn-info">
        <i class="icon-group"></i>
    </a>

    <?= $this->escapeHtml($this->lineup->getName()); ?>
</div>

</div>

<?= $this->form()->openTag($form); ?>

<?= $this->inputVenue(); ?>

<?= $this->formRow($this->form->get('performanceDate')); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-magic"></i>
    Create Performance
</button>

<?= $this->form()->closeTag(); ?>
