<h1>
    <i class="icon-magic"></i>
    Create Performance
</h1>

<h2>
    <i class="icon-cogs"></i>
    <?= $this->escapeHtml($this->lineup->getBand()->getName()); ?>
</h2>

<h3>
    <i class="icon-group"></i>
    <?= $this->escapeHtml($this->lineup->getName()); ?>
</h3>

</h3>
<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('performanceDate')); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->inputVenue(); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-magic"></i>
    Create Performance
</button>

<?= $this->form()->closeTag(); ?>
