<ul class="nav nav-pills pull-right">
    <li>
    <a class="btn-warning" href="/performance/edit?id=<?= $this->performance->getId(); ?>"><i class="icon-magic"></i> Edit Performance</a>
    </li>
</ul>

<h1>
    <li class="icon-magic"></li>
<?php
if ($this->performance->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performance->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performance->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performance->getName()); ?>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->performance->getLineup()->getBand()->getId(); ?>">
        <li class="icon-cogs"></li>
        <?= $this->escapeHtml($this->performance->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h2>
    <a href="/lineup/detail?id=<?= $this->performance->getLineup()->getBand()->getId(); ?>">
        <li class="icon-group"></li>
        <?= $this->escapeHtml($this->performance->getLineup()->getName()); ?>
    </a>
</h2>

<h2>
    <a href="/venue/id=<?= $this->performance->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->performance->getVenue()->getName()); ?>
    </a>
</h2>

<?php
if ($this->performance->getNote()) { ?>
    <pre><?= $this->escapeHtml($this->performance->getNote()); ?></pre>
<?php
}
?>

<h3>Sets</h3>

<ul>
<?php
foreach ($this->performance->getPerformanceSets() as $set) {
#    print_r($performer);
?>
    <li>
        <a href="/set/detail?id=<?= $set->getId(); ?>">
            <?= $this->escapeHtml($set->getName()); ?>
        </a>
    </li>
<?php
}
?>
</ul>


<ul class="nav nav-pills">
    <?php //$this->addSetToPerformance($this->performance->getId(), 'Db\Entity\Lineup', '/lineup/detail?id=' . $this->performance->getId()); ?>
</ul>
