<style>
    .performance-song-detail, .venue-detail {
        display: none;
    }
</style>


<ul class="nav nav-pills pull-right">
<!--
    <li>
        <a class="btn-success" href="/source/create?id=<?= $this->performance->getId(); ?>">
            <i class="icon-headphones"></i>
            Create Source
        </a>
    </li>
-->
    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->performance->getId(); ?>/Db\Entity\Performance">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<div class="h1">
    <a class="btn btn-warning edit-performance" href="#" data-id="<?= $this->performance->getId(); ?>">
        <i class="icon-magic"></i>
    </a>

    <i class="icon-magic"></i>
<?php
if ($this->performance->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performance->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performance->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performance->getName()); ?>
</div>

<?php
if ($this->performance->getNote()) { ?>
    <pre><?= $this->escapeHtml($this->performance->getNote()); ?></pre>
<?php
}
?>

<div class="h1">
    <a class="btn btn-info" href="/band/detail?id=<?= $this->performance->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
    </a>

    <?= $this->escapeHtml($this->performance->getLineup()->getBand()->getName()); ?>

    <a class="btn btn-default" href="#" onClick="$('#performance_drop').toggle();">
        <i class="icon-double-angle-down"></i>
    </a>


    <div id="performance_drop" style="display: none;">

        <div class="h2">
            <a class="btn btn-info" href="/lineup/detail?id=<?= $this->performance->getLineup()->getId(); ?>">
                <i class="icon-group"></i>
            </a>
            <?= $this->escapeHtml($this->performance->getLineup()->getName()); ?>

        <?php
        foreach ($this->performance->getLineup()->getPerformerLineups() as $performerLineup) {
        ?>
            <div class="h3">
                <a class="btn btn-info" href="/performer-lineup/detail?id=<?= $performerLineup->getId(); ?>">
                    <i class="icon-film"></i>
                </a>
                <?= $this->escapeHtml($performerLineup->getPerformer()->getName()); ?>

                <?php
                if ($performerLineup->getNote()) {
                ?>
                    <pre><?= $this->escapeHtml($performerLineup->getNote()); ?></pre>
                <?php
                }
                ?>
            </div>
        <?php
        }
        ?>
            <div class="h2">
                <a href="#" data-id="<?= $performance->getId(); ?>" class="btn btn-success create-performer-performance">
                    <i class="icon-facetime-video"></i>
                </a>
                Guest Performers

</div>
        <?php

        foreach ($this->performance->getPerformerPerformances() as $performerPerformance) {
        ?>
            <div class="h3">
                <a class="btn btn-info" href="/performer/detail?id=<?= $performerPerformance->getPerformer()->getId(); ?>">
                    <i class="icon-film"></i>
                </a>
                <a class="btn btn-warning edit-performer-performance" data-id="<?= $performerPerformance->getId(); ?>" href="">
                    <i class="icon-facetime-video"></i>
                </a>
                <?= $this->escapeHtml($performerPerformance->getPerformer()->getName()); ?>

                <?php
                if ($performerPerformance->getNote()) {
                ?>
                    <pre><?= $this->escapeHtml($performerPerformance->getNote()); ?></pre>
                <?php
                }
                ?>
            </div>
        <?php
        }
        ?>

        </div>

    </div>

</div>

<div class="h1">
    <a class="btn btn-info" href="/venue/detail?id=<?= $this->performance->getVenue()->getId(); ?>">
        <i class="icon-map-marker"></i>
    </a>

    <?= $this->escapeHtml($this->performance->getVenue()->getName()); ?>

    <a class="btn btn-default show-venue-detail" href="#">
        <i class="icon-double-angle-down"></i>
    </a>

    <div class="h2 venue-detail">
        <?= ($this->performance->getVenue()->getCity()) ? $this->escapeHtml($this->performance->getVenue()->getCity()) . '<br>': ''; ?>
        <?= ($this->performance->getVenue()->getState()) ? $this->escapeHtml($this->performance->getVenue()->getState()) . '<br>': ''; ?>
        <?= ($this->performance->getVenue()->getCountry()) ? $this->escapeHtml($this->performance->getVenue()->getCountry()) . '<br>': ''; ?>
        <?= ($this->performance->getVenue()->getZipcode()) ? $this->escapeHtml($this->performance->getVenue()->getZipcode()) . '<br>': ''; ?>
    </div>

</div>


<div class="h1">
    <a href="#" data-id="<?= $performance->getId(); ?>" class="btn btn-success create-performance-set">
        <i class="icon-certificate"></i>
    </a>

    Performance Sets

    <?php
    foreach ($this->performance->getPerformanceSets() as $set) {
    ?>
    <div class="h1">
<!--
        <a class="btn btn-info" href="/performance-set/detail?id=<?= $set->getId(); ?>">
            <i class="icon-certificate"></i>
        </a>
-->
        <a class="btn btn-warning edit-performance-set" href="#" data-id="<?= $set->getId(); ?>">
            <i class="icon-certificate"></i>
        </a>
        <a class="btn btn-success create-performance-set-song" href="#" data-id="<?= $set->getId(); ?>">
            <i class="icon-bolt"></i>
        </a>

        <?= $this->escapeHtml($set->getName()); ?>

    <?php
    if ($set->getNote()) {
    ?>
        <pre><?= $this->escapeHtml($set->getNote()); ?></pre>
    <?php
    }
    ?>

    <?php
    if (sizeof($set->getPerformanceSetSongs())) {
        $count = 1;
        foreach ($set->getPerformanceSetSongs() as $performanceSong) {
    ?>
        <div class="h3">
            <div class="row">
                <div class="span5">
                    <a href="/song/detail?id=<?= $performanceSong->getSong()->getId(); ?>" class="btn btn-info">
                        <i class="icon-music"></i>
                    </a>

                    <a href="#" class="btn btn-warning edit-performance-set-song" data-id="<?= $performanceSong->getId(); ?>">
                        <i class="icon-bolt"></i>
                    </a>

                    <?= $count ++; ?>

                    <?= $this->escapeHtml($performanceSong->getSong()->getName()); ?></a><?php if ($performanceSong->getIsSegue()) echo ' &gt; '; ?>
                        <a class="btn btn-default show-performance-song-detail" href="#" data-id="<?= $performanceSong->getId(); ?>">
                            <i class="icon-double-angle-down"></i>
                        </a>
                </div>

                <div class="performance-song-detail" data-id="<?= $performanceSong->getId(); ?>">

                    <div class="span1">
                        <pre><?= $this->escapeHtml($performanceSong->getLength()); ?>&nbsp;</pre>
                    </div>

                    <div class="span3">
                        <pre><?= $this->escapeHtml($performanceSong->getNote()); ?>&nbsp;</pre>
                    </div>

                </div>
            </div>
        </div>

    <?php
        }
    }
    ?>

    </div>

<?php

}
?>
</div>

</ul>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>
</ul>

<div class="tab-content">
   <div class="tab-pane active" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->performance->getId(), 'Db\Entity\Performance', '/performance/detail?id=' . $this->performance->getId()); ?>
        </ul>

        <?= $this->listComments($this->performance->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <ul class="nav nav-pills">
            <?= $this->createLink($this->performance->getId(), 'Db\Entity\Performance', '/performance/detail?id=' . $this->performance->getId()); ?>
        </ul>
    </div>
</div>


<script>
$(function() {

    $('.show-performance-song-detail').on('click', function(event) {
        $('.performance-song-detail[data-id="' + $(this).attr('data-id') + '"]').toggle();
        return false;
    });

    $('.show-venue-detail').on('click', function(event) {
        $('.venue-detail').toggle();
    });

});
</script>