<h1>
    <i class="icon-magic"></i>
    Edit Performance
</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->inputVenue($this->performance->getVenue()); ?>

<?= $this->formRow($this->form->get('performanceDate')); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-magic"></i>
    Edit Performance
</button>

<a class="btn btn-link" href="/performance/detail?id=<?= $this->performance->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>


<ul class="nav nav-pills">
    <li>
        <a class="btn-success" href="/performance-set/create?id=<?= $this->performance->getId(); ?>">
            <i class="icon-certificate"></i>
            Create Performance Set
        </a>
    </li>

    <?= $this->addPerformerToPerformance($performance->getId()); ?>
    <?= $this->removePerformerFromPerformance($performance->getId()); ?>
</ul>