<h1>States</h1>
<h2><?= $this->escapeHtml($this->country->getName()); ?></h2>

<hr>

<?php

$col1 = $col2 = $col3 = '';
$i = 0;
foreach ($this->states as $state) {
    $i ++;
    switch ($i) {
        case 1:
            $col1[] = $state;
            break;
        case 2:
            $col2[] = $state;
            break;
        case 3:
        default:
            $i = 0;
            $col3[] = $state;
            break;
    }
}

?>


<div class="row">
    <div class="span4">
        <?php
        foreach ($col1 as $entity) {
        ?>
            <h5>
                <a href="/state?countryId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col2 as $entity) {
        ?>
            <h5>
                <a href="/state?countryId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col3 as $entity) {
        ?>
            <h5>
                <a href="/state?countryId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
</div>
