<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-success" href="/performance/create?id=<?= $this->lineup->getId(); ?>"><i class="icon-magic"></i> Create Performane</a>
    </li>

    <li class="">
        <a class="btn-warning" href="/lineup/edit?id=<?= $this->lineup->getId(); ?>"><i class="icon-group"></i> Edit Lineup</a>
    </li>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->lineup->getId(); ?>/Db\Entity\Lineup">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<div class="h1">
    <a class="btn btn-info" href="/band/detail?id=<?= $this->lineup->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
    </a>
    <?= $this->escapeHtml($this->lineup->getBand()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-default" href="/lineup/detail?id=<?= $this->lineup->getId(); ?>">
        <i class="icon-group"></i>
    </a>
    <?= $this->escapeHtml($this->lineup->getName()); ?>

    <?php
    if ($this->lineup->getNote()) { ?>
        <pre><?= $this->escapeHtml($this->lineup->getNote()); ?></pre>
    <?php
    }
    ?>
</div>


<?php
foreach ($this->lineup->getPerformerLineups() as $performerLineup) {
?>
    <h3>
        <a class="btn btn-info" href="/performer-lineup/detail?id=<?= $performerLineup->getId(); ?>">
            <i class="icon-film"></i>
        </a>

        <?= $this->escapeHtml($performerLineup->getPerformer()->getName()); ?>

    <?php
    if ($performerLineup->getNote()) {
    ?>
        <pre><?= $this->escapeHtml($performerLineup->getNote()); ?></pre>
    <?php
    }
    ?>

    </h3>

<?php
}
?>