<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-success" href="/performance/create?id=<?= $this->lineup->getId(); ?>"><i class="icon-magic"></i> Create Performance</a>
    </li>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->lineup->getId(); ?>/Db\Entity\Lineup">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<div class="h1">
        <a class="btn btn-warning edit-lineup" data-id="<?= $this->lineup->getId(); ?>" href="#">
            <i class="icon-group"></i>
        </a>

        <i class="icon-group"></i>
        <?= $this->escapeHtml($this->lineup->getName()); ?>

        <?php
        if ($this->lineup->getNote()) { ?>
            <pre><?= $this->escapeHtml($this->lineup->getNote()); ?></pre>
        <?php
        }
        ?>

    <div class="h2">
        <a class="btn btn-info" href="/band/detail?id=<?= $this->lineup->getBand()->getId(); ?>">
            <i class="icon-cogs"></i>
        </a>
        <?= $this->escapeHtml($this->lineup->getBand()->getName()); ?>
    </div>
</div>



<div class="h1">
    <a class="btn btn-success add-performer-to-lineup" data-id="<?= $this->lineup->getId(); ?>" href="#">
        <i class="icon-facetime-video"></i>
    </a>
    Performers

<?php
foreach ($this->lineup->getPerformerLineups() as $performerLineup) {
?>
    <div class="h2">
        <a class="btn btn-info" href="/performer/detail?id=<?= $performerLineup->getPerformer()->getId(); ?>">
            <i class="icon-film"></i>
        </a>

        <a class="btn btn-warning edit-performer-lineup" data-id="<?= $performerLineup->getId(); ?>" href="#">
            <i class="icon-facetime-video"></i>
        </a>

       <?= $this->escapeHtml($performerLineup->getPerformer()->getName()); ?>

    <?php
    if ($performerLineup->getNote()) {
    ?>
        <pre><?= $this->escapeHtml($performerLineup->getNote()); ?></pre>
    <?php
    }
    ?>

    </div>

<?php
}
?>

</div>