<h1>Edit Lineup</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-group"></i>
    Edit Lineup
</button>

<a class="btn btn-link" href="/lineup/detail?id=<?= $this->lineup->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>

<ul class="nav nav-pills">
    <?= $this->addPerformerToLineup($this->lineup->getId(), 'Db\Entity\Lineup', '/lineup/detail?id=' . $this->lineup->getId()); ?>

    <?= $this->removePerformerFromLineup($this->lineup->getId()); ?>
</ul>
