<h1>
    <i class="icon-bolt"></i>
    Add Song to Performance Set
</h1>

<h1>
    <a href="/performance/detail?id=<?= $this->performanceSet->getPerformance()->getId(); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->performanceSet->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/lineup/detail?id=<?= $this->performanceSet->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-group"></i>
        <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/venue/detail?id=<?= $this->performanceSet->getPerformance()->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->performanceSet->getPerformance()->getVenue()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/performance-set/detail?id=<?= $this->performanceSet->getId(); ?>">
        <i class="icon-certificate"></i>
        <?= $this->escapeHtml($this->performanceSet->getName()); ?>
    </a>
</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->inputSong($this->song); ?>

<?= $this->formRow($this->form->get('length')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<?= $this->formRow($this->form->get('isSegue')); ?>

<br>
<br>

<button type="send" class="btn btn-success">
    <i class="icon-bolt"></i>
    Add Song to Performance Set
</button>

<?= $this->form()->closeTag(); ?>


<ul class="nav nav-pills">
    <li>
        <a href="/song/create" class="btn-success">
            <i class="icon-music"></i>
            Create Song
        </a>
    </li>
</ul>