<style>
    .index {
        display: none;
    }
</style>

<div class="h1">Welcome to www.etreedb.org

<a class="btn btn-default show-index" href="#">
    <i class="icon-double-angle-down"></i>
</a>

    <pre class="index">A community driven open database of live concert information.</pre>

</div>

<script>
$(function() {
    $('.show-index').on('click', function(event) {
        $('.index').toggle();
    });

});
</script>
