<style>
    .index {
        display: none;
    }
</style>

<div class="h1">Welcome to www.etreedb.org

    <a class="btn btn-default show-index" href="#">
        <i class="icon-double-angle-right icon-rotate-90"></i>
    </a>

    <pre class="index">A community driven open database of live concert information.</pre>

</div>

<script>
$(function() {
    $('.show-index').on('click', function(event) {
        $('.index').toggle();
        $('.show-index i').addClass('icon-rotate-90');
    });

});
</script>
