<li class="dropdown">
    <a id="performer-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
        <i class="icon-film"></i>
        <?php echo $this->translate('Performers') ?>
        <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" aria-labelledby="performer-drop" role="menu">

        <li role="menuitem">
            <form class="navbar-search pull-left" id="performer-search" action="/performer/detail">
                <?= $this->inputPerformer(null, 'Create Performer'); ?>
            </form>

            <script>
                $(function() {
                    $('#performer-search').on('submit', function(event) {
                        if ($(this).find('input[name="performer_id"]').val()) {
                            window.location = '/performer/detail?id='
                                + $(this).find('input[name="performer_id"]').val();
                        }

                        return false;
                    });
                });
            </script>
        </li>

        <?php
        if (isset($recent['performers'])) {
        ?><li class="divider"></li>

        <?php
            foreach ($recent['performers'] as $id) {
                if ($p = $this->findPerformer($id)) {
                    ?>
                        <li role="menuitem" class="recent">
                            <a href="/performer/detail?id=<?= $p->getId(); ?>">
                                <i class="icon-film"></i>
                                <?= $this->escapeHtml($p->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>

    </ul>
</li>

<li class="dropdown">
    <a id="band-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
        <i class="icon-cogs"></i>
        <?php echo $this->translate('Bands') ?>
        <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" aria-labelledby="band-drop" role="menu">

        <li role="menuitem">
            <form class="navbar-search pull-left" id="band-search" action="/band/search">
                <?= $this->inputBand(null, 'Create Band'); ?>
            </form>

            <script>
                $(function() {
                    $('#band-search').on('submit', function(event) {
                        if ($(this).find('input[name="band_id"]').val()) {
                            window.location = '/band/detail?id='
                                + $(this).find('input[name="band_id"]').val();
                        }

                        return false;
                    });
                });
            </script>
        </li>

        <?php
        if (isset($recent['bands'])) {
        ?><li class="divider"></li><?php
            foreach ($recent['bands'] as $id) {
                if (!$id) continue;
                if ($p = $this->findEntity('Db\Entity\Band', $id)) {
                    ?>
                        <li role="menuitem">
                            <a href="/band/detail?id=<?= $p->getId(); ?>">
                                <i class="icon-cogs"></i>
                                <?= $this->escapeHtml($p->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>

        <?php
        if (isset($recent['lineups'])) {
        ?><li class="divider"></li><?php
            foreach ($recent['lineups'] as $id) {
                if (!$id) continue;
                if ($p = $this->findEntity('Db\Entity\Lineup', $id)) {
                    ?>
                        <li role="menuitem">
                            <a href="/lineup/detail?id=<?= $p->getId(); ?>">
                                <i class="icon-group"></i>
                                <?= $this->escapeHtml($p->getName()); ?>

                                <i class="icon-cogs"></i>
                                <?= $this->escapeHtml($p->getBand()->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>

    </ul>
</li>


<li class="dropdown">
    <a id="venue-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
        <i class="icon-map-marker"></i>
        <?= $this->translate('Venues'); ?>
        <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" aria-labelledby="venue-drop" role="menu">

        <li role="menuitem">
            <form class="navbar-search pull-left" id="venue-search" action="/venue/search">
                <?= $this->inputVenue(null, $this->translate('Create Venue')); ?>

                <script>
                    $(function() {
                        $('#venue-search').on('submit', function(event) {
                            if ($('form#venue-search input[name="venue_id"]').val()) {
                                window.location = '/venue/detail?id='
                                    + $('form#venue-search [name="venue_id"]').val();
                            }

                            return false;
                        });
                    });
                </script>
            </form>
        </li>

        <?php
        if (isset($recent['venues'])) {
        ?><li class="divider"></li><?php
            foreach ($recent['venues'] as $id) {
                if (!$id) continue;
                if ($v = $this->findVenue($id)) {
                    ?>
                        <li role="menuitem">
                            <a href="/venue/detail?id=<?= $v->getId(); ?>">
                                <i class="icon-map-marker"></i>
                                <?= $this->escapeHtml($v->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>

    </ul>
</li>


<li class="dropdown">
    <a id="performance-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
        <i class="icon-magic"></i>
        <?php echo $this->translate('Performances') ?>
        <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" aria-labelledby="performance-drop" role="menu">
        <li role="menuitem">
            <a class="btn btn-success" id="createPerformance" href="/performance/create" style="color: white;">
                <i class="icon-magic"></i>
                Create Performance
            </a>
        </li>

        <li role="menuitem">
            <form class="navbar-search pull-left" name="search" action="/performance/search">
                <input type="text" name="name" id="name" maxlength="85" size="28" autocomplete="off" placeholder="Search Performances">
            </form>
        </li>

        <?php
        if (isset($recent['performances'])) {
        ?><li class="divider"></li><?php
            foreach ($recent['performances'] as $id) {
                if (!$id) continue;
                if ($p = $this->findEntity('Db\Entity\Performance', $id)) {
                    ?>
                        <li role="menuitem">
                            <a href="/performance/detail?id=<?= $p->getId(); ?>">
                                <i class="icon-magic"></i>
                                <?php
                                if ($p->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
                                    echo $this->escapeHtml($p->getPerformanceDateAt()->format('F d, Y'));
                                } else {
                                    echo $this->escapeHtml($p->getPerformanceDate());
                                }
                                ?>

                                <?= $this->escapeHtml($p->getName()); ?>
                                <i class="icon-cogs"></i>
                                <?= $this->escapeHtml($p->getLineup()->getBand()->getName()); ?>

                                <i class="icon-map-marker"></i>
                                <?= $this->escapeHtml($p->getVenue()->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>
    </ul>
</li>

<li class="dropdown">
    <a id="song-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
        <i class="icon-music"></i>
        <?php echo $this->translate('Songs') ?>
        <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" aria-labelledby="song-drop" role="menu">

        <li role="menuitem">
            <form style="display: inline;">
            <a class="btn btn-info" href="/song">
                <i class="icon-music"></i>
                Browse
            </a>
            </form>
        </li>

        <li role="menuitem">
            <form class="navbar-search pull-left" id="song-search" action="/song/search">
                <?= $this->inputSong(null, $this->translate('Create')); ?>

                <script>
                    $(function() {
                        $('#song-search').on('submit', function(event) {
                            if ($('form#song-search input[name="song_id"]').val()) {
                                window.location = '/song/detail?id='
                                    + $('form#song-search [name="song_id"]').val();
                            }

                            return false;
                        });
                    });
                </script>
            </form>
        </li>

        <?php
        if (isset($recent['songs'])) {
        ?>

        <li class="divider"></li>

        <?php
            foreach ($recent['songs'] as $id) {
                if ($p = $this->findEntity('Db\Entity\Song', $id)) {
                    ?>
                        <li role="menuitem">
                            <a href="/song/detail?id=<?= $p->getId(); ?>">
                                <i class="icon-music"></i>
                                <?= $this->escapeHtml($p->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>
    </ul>
</li>

<!--
<li class="dropdown">
    <a id="source-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
        <i class="icon-headphones"></i>
        <?php echo $this->translate('Sources') ?>
        <b class="caret"></b>
    </a>

    <ul class="dropdown-menu" aria-labelledby="source-drop" role="menu">

        <li role="menuitem">
            <a class="btn btn-success" id="createSource" href="/performance/create" style="color: white;">
                <i class="icon-headphones"></i>
                Create Source
            </a>
        </li>

        <li role="menuitem">
            <form class="navbar-search pull-left" name="search" action="/source/search">
                <input type="text" name="name" id="name" maxlength="85" size="28" autocomplete="off" placeholder="Search Sources">
            </form>
        </li>

        <?php
        if (isset($recent['sources'])) {
        ?><li class="divider"></li><?php
            foreach ($recent['sources'] as $id) {
                if (!$id) continue;
                if ($p = $this->findEntity('Db\Entity\Source', $id)) {
                    ?>
                        <li role="menuitem">
                            <a href="/source/detail?id=<?= $p->getId(); ?>">
                                <i class="icon-headphones"></i>
                                <?= $this->escapeHtml($p->getName()); ?>

                                <i class="icon-magic"></i>
                                <?php
                                if ($p->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
                                    echo $this->escapeHtml($p->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
                                } else {
                                    echo $this->escapeHtml($p->getPerformance()->getPerformanceDate());
                                }
                                ?>

                                <i class="icon-cogs"></i>
                                <?= $this->escapeHtml($p->getPerformance()->getLineup()->getBand()->getName()); ?>

                                <i class="icon-map-marker"></i>
                                <?= $this->escapeHtml($p->getPerformance()->getVenue()->getName()); ?>
                            </a>
                        </li>
                    <?php
                }
            }
        }
        ?>
    </ul>
</li>
-->


<li id="menu-audit">
    <a href="/audit">
        <i class="icon-list"></i>
        Audit Log
    </a>
</li>

<script>

$(function() {
    if (getCookie('editMode') == 'on' && '<?= ($this->zfcUserIdentity()) ? 'loggedin': ''; ?>') {
        $('a#brand.btn').trigger('turnOn');
    } else {
        $('a#brand').trigger('turnOff');
    }
});

$('#createPerformance').on('click', function(event) {
    alert('To create a performance select a lineup from a band');
    return false;
});

$('#createSource').on('click', function(event) {
    alert('To create a source select a performance');
    return false;
});

</script>