<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->performerLineup)
);
?>

<div class="h1">
    <a class="btn btn-info" href="/lineup/detail?id=<?= $this->performerLineup->getLineup()->getId(); ?>">
        <i class="icon-group"></i>
    </a>

    <?= $this->escapeHtml($this->performerLineup->getLineup()->getName()); ?>


    <div class="h2">
        <a class="btn btn-info" href="/band/detail?id=<?= $this->performerLineup->getLineup()->getBand()->getId(); ?>">
            <i class="icon-cogs"></i>
        </a>
        <?= $this->escapeHtml($this->performerLineup->getLineup()->getBand()->getName()); ?>

    </div>

    <a class="btn btn-info" href="/performer/detail?id=<?= $this->performerLineup->getPerformer()->getId(); ?>">
        <i class="icon-film"></i>
    </a>

    <a class="btn btn-warning edit-performer-lineup" data-id="<?= $this->performerLineup->getId(); ?>">
        <i class="icon-bolt"></i>
    </a>

    <?= $this->escapeHtml($this->performerLineup->getPerformer()->getName()); ?>

    <?php
    if ($this->performerLineup->getNote()) {
    ?>
        <pre><?= $this->escapeHtml($this->performerLineup->getNote()); ?></pre>
    <?php
    }
    ?>

</div>