<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-facetime-video"></i>
            Edit Performer Lineup
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('note')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-warning">
            <i class="icon-facetime-video"></i>
            Edit Performer Lineup
        </button>

        <a class="confirm btn btn-danger" href="<?=
            $this->url('performer-lineup/delete', array(
                'id' => $this->id,
            )); ?>">
            <i class="icon-facetime-video"></i>
            Remove Performer from Lineup
        </a>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>

$(function() {
    $('form#performer-lineup').attr('id', 'performer-lineup<?= $id; ?>');
    $('form#performer-lineup<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '<?=
                $this->url('performer-lineup/edit', array(
                    'id' => $this->performerLineup->getId(),
                )); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});

</script>