<h1>
    <a class="btn-info btn" href="/audit">
        <i class="icon-list"></i>
    </a>
    Audit Log
</h1>

<div class="row">
    <div class="span12">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>Revision</th>
                    <th>Timestamp</th>
                    <th>Entities</th>
                    <th>User</th>
                    <th>Comments</th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <td colspan="6">
                        <ul class="nav nav-pills">
                            <li>
                                <a href="#" class="btn-success">Insert</a>
                            </li>
                            <li>
                                <a href="#" class="btn-warning">Update</a>
                            </li>
                            <li>
                                <a href="#" class="btn-danger">Delete</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <?php
                $i = 1 ;
                foreach ($revisions as $revision) {
                ?>
                    <tr>
                        <td>
                            <a href="<?=
                                $this->url('audit_viewrevision',
                                    array(
                                        'rev' => $revision->getId()
                                    )
                                );
                            ?>">
                                <?php  echo $this->escapeHtml($revision->getId()); ?>
                            </a>
                        </td>

                        <td>
                            <a href="<?=
                                $this->url('audit_viewrevision',
                                    array(
                                        'rev' => $revision->getId()
                                    )
                                );
                            ?>">

                                <?= $revision->getTimestamp()->format('r'); ?>

                            </a>
                        </td>

                        <td>
                        <?php
                        $changedEntities = $this->auditReader->findEntitesChangedAtRevision($revision->getId());
                        foreach ($changedEntities as $ce) {
                        ?>
                                <?php $id = $ce->getId(); ?>

                                    <a class="btn-info btn" href="/<?= $this->routeMap[$ce->getClassName()]; ?>/detail?id=<?= $id['id']; ?>"><i class="<?= $this->iconMap[$ce->getClassName()]; ?>"></i></a>

                                        <a href="<?php
                                            switch ($ce->getRevisionType()) {
                                                case 'INS':
                                                    $buttonClass = 'btn-success';
                                                    break;
                                                case 'UPD':
                                                    $buttonClass = 'btn-warning';
                                                    break;
                                                case 'DEL':
                                                    $buttonClass = 'btn-danger';
                                                    break;
                                                default:
                                                    $buttonClass = 'btn-info';
                                            }

                                        echo $this->url(
                                            'audit_viewentity',
                                            array(
                                                'id' => $id['id'],
                                                'className' => $ce->getClassName(),
                                            )
                                        );?>" class="<?= $buttonClass; ?> btn">

                                        <?= $this->escapeHtml($ce->getClassName()); ?>
                                    </a>

                        <?php
                        $i++;
                        }
                        ?>

                        </td>

                        <td>
                            <a class="btn btn-default" href="/user/<?= $this->escapeHtml($revision->getUser()->getUserName()); ?>">
                                <i class="icon-user"></i>
                                <?= $this->escapeHtml($revision->getUser()->getDisplayName()); ?>
                            </a>
                        </td>

                        <td>
                            <?= sizeof($revision->getComments()); ?>
                        </td>
                    </tr>
                <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</div>