<h1>Audit Log</h1>

<div class="row">
    <div class="span12">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th>Revision</th>
                    <th>Timestamp</th>
                    <th>Entities</th>
                    <th>User</th>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <td colspan="6">
                        <span class="label label-success">Insert</span>
                        <span class="label label-warning">Update</span>
                        <span class="label label-important">Delete</span>
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <?php
                $i = 1 ;
                foreach ($revisions as $revision) {
                ?>
                    <tr>
                        <td>
                            <a href="<?=
                                $this->url('audit_viewrevision',
                                    array(
                                        'rev' => $revision->getId()
                                    )
                                );
                            ?>">
                                <?php  echo $this->escapeHtml($revision->getId()); ?>
                            </a>
                        </td>

                        <td>
                            <a href="<?=
                                $this->url('audit_viewrevision',
                                    array(
                                        'rev' => $revision->getId()
                                    )
                                );
                            ?>">

                                <?= $revision->getTimestamp()->format('r'); ?>

                            </a>
                        </td>

                        <td>
                        <?php
                        $changedEntities = $this->auditReader->findEntitesChangedAtRevision($revision->getId());
                        foreach ($changedEntities as $ce) {
                        ?>
                                <?php $id = $ce->getId(); ?>
                                <a href="<?=
                                    $this->url(
                                        'audit_viewentity',
                                        array(
                                            'id' => $id['id'],
                                            'className' => $ce->getClassName(),
                                        )
                                    );?>">
                            <span class="label label-<?php
                                switch ($ce->getRevisionType()) {
                                    case 'INS':
                                        echo 'success';
                                        break;
                                    case 'UPD':
                                        echo 'warning';
                                        break;
                                    case 'DEL':
                                        echo 'important';
                                        break;
                                    default:
                                        echo 'info';
                                }
                            ?>">


                                    <?php  echo $this->escapeHtml($ce->getClassName()); ?>
                            </span>
                                </a>
                        <br>
                        <?php
                        $i++;
                        }
                        ?>
                        </td>

                        <td>
                            <span class="label label-info">
                                <?= $this->escapeHtml($revision->getUser()->getDisplayName()); ?>
                            </span>
                        </td>
                    </tr>
                <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</div>