<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-info" href="/<?= $this->routeMap[$className]; ?>/detail?id=<?= $this->id; ?>">
            <i class="<?= $this->iconMap[$className]; ?>"></i>

            <?php
            if ($p = $this->findEntity($className, $id)) {
            ?>
                <?php if (method_exists($p, 'getName')) echo $this->escapeHtml($p->getName()); ?>
            <?php
            }
            ?>

        </a>
    </li>
</ul>

<h1>
    <a class="btn-info btn" href="/audit">
        <i class="icon-list"></i>
    </a>
    <?php
        strtok($className, '\\');
        strtok('\\');
        $entityName = strtok('\\');
        preg_match_all('/((?:^|[A-Z])[a-z]+)/', $entityName, $matches);
        print_r(implode(' ', $matches[1]));
    ?>
</h1>

<form action="<?=
    $this->url('audit_compare',
        array(
            'id' => $id ,
            'className' => $className
        )
    );
    ?>" method="post">

<div class="row">
    <div class="span12">
        <table class="table table-striped table-hover table-bordered">

            <thead>
                <tr>
                    <th colspan="3">&nbsp;</th>
                    <th colspan="2">Compare</th>
                </tr>
                <tr>
                    <th>Revision</th>
                    <th>Timestamp</th>
                    <th>User</th>
                    <th>Old</th>
                    <th>New</th>
                </tr>
            </thead>

            <tbody>
                <?php
                $i = 0;
                foreach ($revisions  as $revision) {
                ?>

                <tr>
                    <td>
                        <a href="<?=
                            $this->url('audit_viewdetails',
                            array(
                                'id' => $id ,
                                'className' => $className,
                                'rev' =>$revision->getId()
                            )
                        ); ?>">
                            <?= $this->escapeHtml($revision->getId()); ?>
                        </a>
                    </td>
                    <td>
                        <a href="<?=
                            $this->url('audit_viewdetails',
                            array(
                                'id' => $id ,
                                'className' => $className,
                                'rev' =>$revision->getId()
                            )
                        ); ?>">
                            <?= $revision->getTimestamp()->format('r'); ?>
                        </a>
                    </td>
                    <td>

                            <a class="btn btn-default" href="/user/<?= $this->escapeHtml($revision->getUser()->getUsername()); ?>">
                                <?php echo $this->gravatar($revision->getUser()->getEmail(), array('img_size' => 24)); ?>
                                <?= $revision->getUser()->getDisplayName(); ?>
                            </a>

                    </td>

                    <td>
                        <input type="radio" name="oldRev" value="<?php  echo $this->escapeHtml($revision->getId()); ?>"
                            <?php echo  (sizeof($revisions) == 1 or $i == 1) ? 'checked="checked"': ''; ?> />
                    </td>
                    <td>
                        <input type="radio" name="newRev" value="<?php  echo $this->escapeHtml($revision->getId()); ?>"
                            <?php echo  (!$this->escapeHtml($i)) ? 'checked="checked"': ''; ?> />
                    </td>
                </tr>
                <?php
                    $i++;
                }
                ?>

            </tbody>

        </table>
    </div>
</div>

<div class="row">
    <div class="span12">
        <button type="send" class="btn btn-primary">
            <i class="icon-exchange"></i>
            Compare revisions
        </button>
    </div>
</div>

</form>
