<h1>
    <a class="btn-info btn" href="/audit">
        <i class="icon-list"></i>
    </a>
    Entities changed in revision <?= $this->escapeHtml($this->revision->getId()); ?>
</h1>

<div class="row">
    <div class="span12">
        <table class="table table-striped table-hover table-bordered ">
            <thead>
                <tr>
                    <td>Id</td>
                    <td>Entity Name</td>
                    <td>Entity details</td>
                </tr>
            </thead>

            <tfoot>
                <tr>
                    <td colspan="6">
                        <ul class="nav nav-pills">
                            <li>
                                <a href="#" class="btn-success">Insert</a>
                            </li>
                            <li>
                                <a href="#" class="btn-warning">Update</a>
                            </li>
                            <li>
                                <a href="#" class="btn-danger">Delete</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            </tfoot>

            <tbody>
                <?php foreach ($changedEntities as $ce): ?>
                    <tr>
                        <?php $id = $ce->getId(); ?>
                        <td>
                            <a href="<?php echo $this->url("audit_viewdetails",array("id" => $id["id"] , "className" => $ce->getClassName(), "rev" =>$revision->getId() ));?>">
                                <?php echo $this->escapeHtml($id["id"]);?></a>
                        </td>
                        <td>
                            <a href="<?php
                                switch ($ce->getRevisionType()) {
                                    case 'INS':
                                        $buttonClass = 'btn-success';
                                        break;
                                    case 'UPD':
                                        $buttonClass = 'btn-warning';
                                        break;
                                    case 'DEL':
                                        $buttonClass = 'btn-danger';
                                        break;
                                    default:
                                        $buttonClass = 'btn-info';
                                }

                            echo $this->url(
                                'audit_viewentity',
                                array(
                                    'id' => $id['id'],
                                    'className' => $ce->getClassName(),
                                )
                            );?>" class="btn <?= $buttonClass; ?>">

                            <?= $this->escapeHtml($ce->getClassName()); ?>
                        </a>
                    </td>

                        <td>
                        <?php

                            $entity = $ce->getEntity();
                            $em->detach($entity);

                            var_dump($entity);

                        ?></td>
                    </tr>
                <? endforeach; ?>
            </tbody>

        </table>
    </div>
</div>

<ul class="nav nav-pills">
<?= $this->createComment($this->revision->getId(), 'Audit\Entity\Revision', '/audit/revision/' . $this->revision->getId()); ?>
</ul>

<?= $this->listComments($this->revision->getComments());
