<ul class="nav nav-pills pull-right">
    <li class="dropdown">
        <a id="action-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
            <?php echo $this->translate('Actions') ?>
            <b class="caret"></b>
        </a>

        <ul class="dropdown-menu" aria-labelledby="action-drop" role="menu">

            <li role="menuitem">
                <a href="/country/create">Create Country</a>
            </li>

            <li role="menuitem">
                <a href="/country/merge">Merge Countries</a>
            </li>

        </ul>
    </li>
</ul>


<h1>Countries</h1>

<hr>

<?php

$col1 = $col2 = $col3 = array();
$i = 0;
foreach ($this->countries as $country) {
    $i ++;
    switch ($i) {
        case 1:
            $col1[] = $country;
            break;
        case 2:
            $col2[] = $country;
            break;
        case 3:
        default:
            $i = 0;
            $col3[] = $country;
            break;
    }
}

?>


<div class="row">
    <div class="span4">
        <?php
        foreach ($col1 as $entity) {
        ?>
            <h5>
                <a href="/state?countryId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col2 as $entity) {
        ?>
            <h5>
                <a href="/state?countryId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col3 as $entity) {
        ?>
            <h5>
                <a href="/state?countryId=<?= $entity->getId(); ?>">
                    <?= $this->escapeHtml($entity->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
</div>
