<h1>Countries</h1>

<hr>

<?php

$col1 = $col2 = $col3 = '';
$i = 0;
foreach ($this->countries as $country) {
    $i ++;
    switch ($i) {
        case 1:
            $col1[] = $country;
            break;
        case 2:
            $col2[] = $country;
            break;
        case 3:
        default:
            $i = 0;
            $col3[] = $country;
            break;
    }
}

?>


<div class="row">
    <div class="span4">
        <?php
        foreach ($col1 as $country) {
        ?>
            <h5>
                <a href="/country/detail?id=<?= $country->getId(); ?>">
                    <?= $this->escapeHtml($country->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col2 as $country) {
        ?>
            <h5>
                <a href="/country/detail?id=<?= $country->getId(); ?>">
                    <?= $this->escapeHtml($country->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
    <div class="span4">
        <?php
        foreach ($col3 as $country) {
        ?>
            <h5>
                <a href="/country/detail?id=<?= $country->getId(); ?>">
                    <?= $this->escapeHtml($country->getName()); ?>
                </a>
             </h5>
        <?php
        }
        ?>
    </div>
</div>
