<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-certificate"></i>
            Create Performance Set
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('note')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-success">
            <i class="icon-certificate"></i>
            Create Performance Set
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('form#performance-set').attr('id', 'performance-set<?= $id; ?>');
    $('form#performance-set<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '<?=
                $this->url('performance-set/create', array(
                    'id' => $this->id,
                )); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});
</script>