<h1>
    <i class="icon-certificate"></i>
    Create Performance Set
</h1>

<h1>
    <a href="/performance/detail?id=<?= $this->performance->getId(); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->performance->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performance->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performance->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performance->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->performance->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->performance->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/venue/detail?id=<?= $this->performance->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->performance->getVenue()->getName()); ?>
    </a>
</h1>


<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-certificate"></i>
    Create Performance Set
</button>

<a class="btn btn-link" href="/performance/detail?id=<?= $this->performance->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>



