<ul class="nav nav-pills pull-right">
    <li>
        <a class="btn-warning" href="/performance-set/edit?id=<?= $this->performanceSet->getId(); ?>">
            <i class="icon-certificate"></i>
            Edit Performance Set
        </a>
    </li>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->performanceSet->getId(); ?>/Db\Entity\PerformanceSet">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<h1>
    <a href="/performance/detail?id=<?= $this->performanceSet->getPerformance()->getId(); ?>">
    <i class="icon-magic"></i>
<?php
if ($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/band/detail?id=<?= $this->performanceSet->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/lineup/detail?id=<?= $this->performanceSet->getPerformance()->getLineup()->getBand()->getId(); ?>">
        <i class="icon-group"></i>
        <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getName()); ?>
    </a>
</h1>

<h1>
    <a href="/venue/detail?id=<?= $this->performanceSet->getPerformance()->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($this->performanceSet->getPerformance()->getVenue()->getName()); ?>
    </a>
</h1>

<?php
if ($this->performanceSet->getPerformance()->getNote()) { ?>
    <pre><?= $this->escapeHtml($this->performanceSet->getPerformance()->getNote()); ?></pre>
<?php
}
?>

<h1>
    <i class="icon-certificate"></i>
    <?= $this->escapeHtml($this->performanceSet->getName()); ?>
</h1>

<?php
if (sizeof($this->performanceSet->getPerformanceSongs())) {
    foreach ($this->performanceSet->getPerformanceSongs() as $performanceSong) {
?>
        <div class="row">
            <div class="span5">
                <pre><i class="icon-music"></i> <?= $this->escapeHtml($performanceSong->getSong()->getName()); ?><?php if ($performanceSong->getIsSegue()) echo ' &gt; '; ?></pre>
            </div>

            <div class="span7">
                <pre><?= $this->escapeHtml($performanceSong->getNote()); ?>&nbsp;</pre>
            </div>
        </div>

<?php
    }
}
?>

<?php
if ($this->performanceSet->getNote()) {
?>
    <pre><?= $this->escapeHtml($this->performanceSet->getNote()); ?></pre>
<?php
}
?>
