<a class="pull-right btn-success btn create-performance-set-song" href="#" data-id="<?= $this->performanceSet->getId(); ?>">
    <i class="icon-music"></i>
    Add Song to Performace Set
</a>

<a class="pull-right btn-warning" href="<?=
    $this->url('performance-set/edit', array(
        'id' => $this->performanceSet->getId(),
    )); ?>">
    <i class="icon-certificate"></i>
    Edit Performance Set
</a>

<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->performanceSet)
);
?>

<div class="h1">
    <a class="btn btn-info" href="<?=
        $this->url('performance/detail', array(
            'id' => $this->performanceSet->getPerformance()->getId(),
        )); ?>">
        <i class="icon-magic"></i>
    </a>
<?php
if ($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-info" href="<?=
        $this->url('band/detail', array(
            'id' => $this->performanceSet->getPerformance()->getLineup()->getBand()->getId(),
        )); ?>">
        <i class="icon-cogs"></i>
    </a>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getBand()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-info" href="<?=
        $this->url('lineup/detail', array(
            'id' => $this->performanceSet->getPerformance()->getLineup()->getBand()->getId(),
        )); ?>">
        <i class="icon-group"></i>
    </a>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getName()); ?>
</div>

<div class="h1">
    <a class="btn btn-info" href="<?=
        $this->url('venue/detail', array(
            'id' => $this->performanceSet->getPerformance()->getVenue()->getId(),
        )); ?>">
        <i class="icon-map-marker"></i>
    </a>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getVenue()->getName()); ?>
</div>

<div class="h1">
    <i class="icon-certificate"></i>
    <?= $this->escapeHtml($this->performanceSet->getName()); ?>
</div>

<?php
if (sizeof($this->performanceSet->getPerformanceSetSongs())) {
    $count = 1;
    foreach ($this->performanceSet->getPerformanceSetSongs() as $performanceSong) {
?>
        <div class="row">
            <div class="span1">
                <pre><?= $count ++; ?></pre>
            </div>

            <div class="span5">
                <pre><i class="icon-music"></i> <?= $this->escapeHtml($performanceSong->getSong()->getName()); ?><?php if ($performanceSong->getIsSegue()) echo ' &gt; '; ?></pre>
            </div>

            <div class="span1">
                <pre><?= $this->escapeHtml($performanceSong->getLength()); ?>&nbsp;</pre>
            </div>

            <div class="span5">
                <pre><?= $this->escapeHtml($performanceSong->getNote()); ?>&nbsp;</pre>
            </div>
        </div>

<?php
    }
}
?>

<?php
if ($this->performanceSet->getNote()) {
?>
    <pre><?= $this->escapeHtml($this->performanceSet->getNote()); ?></pre>
<?php
}
?>
