<h1>
    <i class="icon-certificate"></i>
    Edit Performance Set
</h1>

<h1>
    <i class="icon-magic"></i>
<?php
if ($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getName()); ?>
</h1>

<h1>
    <i class="icon-cogs"></i>
    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getBand()->getName()); ?>
</h1>

<h1>
    <i class="icon-map-marker"></i>
    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getVenue()->getName()); ?>
</h1>

<h1>
    <i class="icon-group"></i>
    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getName()); ?>
</h1>

<?php
if (sizeof($this->performanceSet->getPerformanceSongs())) {
    foreach ($this->performanceSet->getPerformanceSongs() as $performanceSong) {
?>
        <div class="row">
            <div class="span5">
                <pre><a href="/performance-song/detail?id=<?= $performanceSong->getId(); ?>"><i class="icon-music"></i> <?= $this->escapeHtml($performanceSong->getSong()->getName()); ?><?php if ($performanceSong->getIsSegue()) echo ' &gt; '; ?></a></pre>
            </div>

            <div class="span7">
                <pre><?= $this->escapeHtml($performanceSong->getSong()->getNote()); ?></pre>
            </div>
        </div>

<?php
    }
}
?>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<?= $this->formRow($this->form->get('sort')); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-certificate"></i>
    Edit Performance Set
</button>

<a class="btn btn-link" href="/performance-set/detail?id=<?= $this->performanceSet->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>

<ul class="nav nav-pills">
    <li>
        <a class="btn-success" href="/performance-song/create?id=<?= $this->performanceSet->getId(); ?>">
            <i class="icon-music"></i>
            Add Song to Performace Set
        </a>
    </li>
</ul>
