<h1>
    <i class="icon-certificate"></i>
    Edit Performance Set
</h1>

<h1>
    <i class="icon-magic"></i>
<?php
if ($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($this->performanceSet->getPerformance()->getPerformanceDate());
}
?>

    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getName()); ?>
</h1>

<h1>
    <i class="icon-cogs"></i>
    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getBand()->getName()); ?>
</h1>

<h1>
    <i class="icon-map-marker"></i>
    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getVenue()->getName()); ?>
</h1>

<h1>
    <i class="icon-group"></i>
    <?= $this->escapeHtml($this->performanceSet->getPerformance()->getLineup()->getName()); ?>
</h1>

<?php
if (sizeof($this->performanceSet->getPerformanceSongs())) {
?>
<div id="sortSongs">
<?php
    foreach ($this->performanceSet->getPerformanceSongs() as $performanceSong) {
?>
        <div class="row" id="performanceSong_<?= $performanceSong->getId(); ?>">
            <div class="span5">
                <pre><a href="/performance-song/detail?id=<?= $performanceSong->getId(); ?>"><i class="icon-music"></i> <?= $this->escapeHtml($performanceSong->getSong()->getName()); ?><?php if ($performanceSong->getIsSegue()) echo ' &gt; '; ?></a></pre>
            </div>

            <div class="span6">
                <pre><?= $this->escapeHtml($performanceSong->getNote()); ?>&nbsp;</pre>
            </div>

            <div class="span1">
                <pre><i class="icon-sort"></i></pre>
            </div>
        </div>

<?php
    }
?>
</div>
<?php
}
?>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-certificate"></i>
    Edit Performance Set
</button>

<a class="btn btn-link" href="/performance-set/detail?id=<?= $this->performanceSet->getId(); ?>">
    cancel
</a>

<?= $this->form()->closeTag(); ?>

<ul class="nav nav-pills">
    <li>
        <a class="btn-success" href="/performance-song/create?id=<?= $this->performanceSet->getId(); ?>">
            <i class="icon-music"></i>
            Add Song to Performace Set
        </a>
    </li>
</ul>

<script>
require(['jquery-ui.min'], function() {
    $('#sortSongs').sortable({
        update: function(event, ui) {
            $.get('/performance-set/sort-performance-songs', {
                id: <?= $this->performanceSet->getId(); ?>,
                sort: $(this).sortable('toArray').toString()
            });
        }
    });
});
</script>