<ul class="nav nav-pills pull-right">
    <li class="">
        <a class="btn-warning" href="/performer-alias/edit?id=<?= $this->performerAlias->getId(); ?>"><i class="icon-film"></i> Edit Performer Alias</a>
    </li>

    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->performerAlias->getId(); ?>/Db\Entity\PerformerAlias">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>


<h1>
    <i class="icon-film"></i>
    <a href="/performer/detail?id=<?= $this->performerAlias->getPerformer()->getId(); ?>">
        <?= $this->escapeHtml($this->performerAlias->getPerformer()->getLastname()); ?>
        <?php if ($this->escapeHtml($this->performerAlias->getPerformer()->getLastname())) echo ', '; ?>
        <?= $this->escapeHtml($this->performerAlias->getPerformer()->getFirstname()); ?>
    </a>
</h1>

<h1>
    <i class="icon-facetime-video"></i>
    <?= $this->escapeHtml($this->performerAlias->getName()); ?>
</h1>

<?php
if ($this->escapeHtml($this->performerAlias->getNote())) {
?>
    <pre><?= $this->escapeHtml($this->performerAlias->getNote()); ?></pre>
<?php
}
?>
