<h1>
    <i class="icon-facetime-video"></i>
    Edit Performer Alias
</h1>

<h1>
    <i class="icon-film"></i>
    <?= $this->escapeHtml($this->performerAlias->getPerformer()->getName()); ?>
</h3>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')->setLabel('Alias')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-film"></i>
    Edit Performer Alias
</button>

<?= $this->form()->closeTag(); ?>
