<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-music"></i>
            Create Song
        </h1>
    </div>

    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?= $this->formRow($this->form->get('mbid')); ?>

        <?= $this->inputBand(); ?>

        <?= $this->formRow($this->form->get('note')); ?>

    </div>

    <div class="modal-footer">
        <button type="send" class="btn btn-success">
            <i class="icon-music"></i>
            Create Song
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>
    </div>

<?= $this->form()->closeTag(); ?>

<script>
$(function() {

    $('form#song').attr('id', 'song<?= $id; ?>');
    $('form#song<?= $id; ?>').on('submit', function(event) {

        $.ajax({
            url: '/song/create',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                }
            }
        });

        return false;
    });
});

</script>