<ul class="nav nav-pills pull-right">
    <li>
        <a class="btn-info" href="/audit/entity/<?= $this->song->getId(); ?>/Db\Entity\Song">
            <i class="icon-list"></i>
        </a>
    </li>
</ul>

<div class="h1">
    <a href="#" class="btn btn-warning edit-song" data-id="<?= $this->song->getId(); ?>">
        <i class="icon-music"></i>
    </a>

    <i class="icon-music"></i>
    <?= $this->escapeHtml($this->song->getName()); ?>

    <?php
        if ($this->song->getBand()) {
    ?>
        <div class="h2">
            <a class="btn btn-info" href="/band/detail?id=<?= $this->song->getBand()->getId(); ?>">
                <i class="icon-cogs"></i>
            </a>
            <?= $this->escapeHtml($this->song->getBand()->getName()); ?>

        </div>
    <?php
    }
    ?>

    <?php
    if ($this->song->getNote()) { ?>
        <pre><?= $this->escapeHtml($this->song->getNote()); ?></pre>
    <?php
    }
    ?>
</div>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#performances" data-toggle="tab">
            Performances
        </a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="performances">
        <ul class="nav nav-pills">
            <?= $this->listPerformances($this->song->getPerformances()); ?>
        </ul>
    </div>
</div>