<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->song)
);
?>

<div class="h1">
    <a href="#" class="btn btn-warning edit-song" data-id="<?= $this->song->getId(); ?>">
        <i class="icon-music"></i>
    </a>

    <i class="icon-music"></i>
    <?= $this->escapeHtml($this->song->getName()); ?>

    <?php
        if ($this->song->getBand()) {
    ?>
        <div class="h2">
            <a class="btn btn-info" href="/band/detail?id=<?= $this->song->getBand()->getId(); ?>">
                <i class="icon-cogs"></i>
            </a>
            <?= $this->escapeHtml($this->song->getBand()->getName()); ?>

        </div>
    <?php
    }
    ?>

    <?php
    if ($this->song->getNote()) { ?>
        <pre><?= $this->escapeHtml($this->song->getNote()); ?></pre>
    <?php
    }
    ?>
</div>

<ul class="nav nav-tabs" id="tabs">
    <li class="active">
        <a href="#performances" data-toggle="tab">
            Performances
        </a>
    </li>

    <li class="<?php if (!$this->song->getPerformances()) echo 'active'; ?>">
        <a href="#comments" data-toggle="tab">
            Comments
        </a>
    </li>

    <li class="">
        <a href="#links" data-toggle="tab">
            Links
        </a>
    </li>

</ul>


<div class="tab-content">
    <div class="tab-pane active" id="performances">
        <ul class="nav nav-pills">
            <?= $this->listPerformances($this->song->getPerformances()); ?>
        </ul>
    </div>

   <div class="tab-pane <?php if (!$this->song->getPerformances()) echo 'active'; ?>" id="comments">
        <ul class="nav nav-pills">
            <?= $this->createComment($this->song->getId(), 'Db\Entity\Song', '/song/detail?id=' . $this->song->getId()); ?>
        </ul>

        <?= $this->listComments($this->song->getComments()); ?>
    </div>

    <div class="tab-pane" id="links">
        <?= $this->createLink($this->song->getId(), 'Db\Entity\Song', '/song/detail?id=' . $this->song->getId()); ?>

        <?= $this->listLinks($this->song->getLinks()); ?>
    </div>
</div>

