<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-music"></i>
            Edit Song
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('name')); ?>

        <?=
        $this->partial('db-etree-org/partial/lookup', [
            'label' => "<a class=\"btn btn-success create-band\" href='#' title=\"Create Band\"><i class=\"icon-cogs\"></i> Band</a>",
            'element' => $this->form->get('band'),
            'route' => 'band/searchJson',
        ]);
        ?>

        <?= $this->formRow($this->form->get('mbid')); ?>

        <?= $this->formRow($this->form->get('note')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-warning">
            <i class="icon-music"></i>
            Edit Song
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>
$(function() {
    $('form#song').attr('id', 'song<?= $id; ?>');
    $('form#song<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '<?=
                $this->url('song/edit', array(
                    'songId' => $this->song->getId(),
                )); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});
</script>