<h1>
    <i class="icon-music"></i>
    Edit Song
</h1>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('name')); ?>

<?= $this->formRow($this->form->get('mbid')); ?>

<?= $this->inputBand($this->song->getBand()); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-success">
    <i class="icon-music"></i>
    Edit Song
</button>

<?= $this->form()->closeTag(); ?>
