<div class="h1">
    <i class="icon-music"></i>
    Songs
</div>

<div class="row">
    <?php

    foreach ($songs as $index => $song) {
    ?>
        <div class="span4" style="padding: 4px;">
            <a class="btn btn-info" href="/song/detail?id=<?= $song->getId(); ?>">
                <i class="icon-music"></i>
            </a>

            <?= $this->escapeHtml($song->getName()); ?>
        </div>
    <?php
    }
    ?>
</div>