    <a class="btn btn-success" href="#" onClick="
        $('#addChecksumToSourceSpan').modal();
        return false;
        ">
        <i class="icon-ok-circle"></i>
        Add
    </a>

<span class="modal hide" id="addChecksumToSourceSpan">
    <form method="post" action="/checksum/create?id=<?= $this->id; ?>">

        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>
                <i class="icon-headphones"></i>
                Add Checksum to Source
            </h3>
        </div>

        <div class="modal-body">

            <input type="hidden" name="id" value="<?= $id; ?>">

            <label for="name">Name</label>
            <input type="text" name="name">

            <label for="content">Content</label>
            <textarea name="content" id="content_checksum"></textarea>

            <?= $this->PasteUpload('content_checksum', 'Paste Uploaded File to Content'); ?>

        </div>

        <div class="modal-footer">

            <button type="send" class="btn btn-success">
                <i class="icon-headphones"></i>
                Add Checksum to Source
            </button>

            <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
                Cancel
            </button>

        </div>

    </form>
</span>
