
<li>
    <a class="btn-success" href="#" onClick="
//        $('#createPerformerPerformanceSpan').load('/performance/add-performer?id=<?= $this->id; ?>');
        $('#createPerformerPerformanceSpan').modal();

        ">
        <i class="icon-film"></i>
        Add
    </a>
</li>

<span class="modal hide" id="createPerformerPerformanceSpan">
<form method="post" action="/performance/add-performer?id=<?= $id; ?>">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>
        <i class="icon-film"></i>
        Add Performer to Performance
    </h3>
    </div>
    <div class="modal-body">

        <input type="hidden" name="id" value="<?= $id; ?>">

        <?= $this->inputPerformer(); ?>

        <label for="note">Note</label>
        <textarea name="note"></textarea>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-success">
            <i class="icon-"></i>
            Add Performer to Performance
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>


    </div>
</form>
</span>