<li class="">
    <a onClick="$('#createComment').modal();"  class="btn-success" href="#"><i class="icon-comment"></i> Create Comment</a>
</li>


    <div id="createComment" class="modal hide fade">
    <form method="post" action="/comment/create" id="createCommentForm">
        <input type="hidden" name="id" value="<?= $id; ?>">
        <input type="hidden" name="entityName" value="<?= $entityName; ?>">
        <input type="hidden" name="returnUrl" value="<?= $returnUrl; ?>">

    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Create Comment</h3>
    </div>
    <div class="modal-body">

        <label for="rating">Rating</label>
        <span class="rating">
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
        </span>

        <label for="note">Note</label>
        <textarea name="note"></textarea>


    </div>
    <div class="modal-footer">

    <a href="#" onClick="$('#createCommentForm').submit();"  class="btn btn-success">
        <i class="icon-comment"></i>
        Save Comment
    </a>
    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
        Cancel
    </button>
    </div>
    </form>
</div>


