<li class="">
    <a onClick="$('#createLink').toggle();"  class="btn-success" href="#"><i class="icon-bookmark"></i> Create Link</a>
</li>


    <div id="createComment" class="modal hide fade">
    <form method="post" action="/link/create" id="createLinkForm">
        <input type="hidden" name="id" value="<?= $id; ?>">
        <input type="hidden" name="entityName" value="<?= $entityName; ?>">
        <input type="hidden" name="returnUrl" value="<?= $returnUrl; ?>">

        <div class="row">
            <div class="span1">
                Title
            </div>
            <div class="span11">
                <input type="text" maxlength="255" name="title">
            </div>
        </div>
        <div class="row">
            <div class="span1">
                URL
            </div>
            <div class="span11">
                <input type="text" maxlength="255" name="url">
            </div>
        </div>
        <div class="row">
            <div class="span1">
                Note
            </div>
            <div class="span11">
                <textarea name="note"></textarea>
            </div>
        </div>

        <div class="row">
            <div class="span1">
                &nbsp;
            </div>
            <div class="span11">
                <button class="btn btn-info" type="send">
                    <i class="icon-save"></i>
                    Submit
                </button>
            </div>


    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Create Link</h3>
    </div>
    <div class="modal-body">

        <label for="rating">Rating</label>
        <span class="rating">
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
            <span class="star"></span>
        </span>

        <label for="note">Note</label>
        <textarea name="note"></textarea>


    </div>
    <div class="modal-footer">

    <a href="#" onClick="$('#createCommentForm').submit();"  class="btn btn-success">
        <i class="icon-comment"></i>
        Save Comment
    </a>
    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
        Cancel
    </button>
    </div>
    </form>
</div>