<li class="">
    <a onClick="$('#createLink').toggle();"  class="btn-success" href="#"><i class="icon-external-link"></i> Create Link</a>
</li>

<div style="display: none; clear: both;" id="createLink">

    <form method="post" action="/link/create">
        <input type="hidden" name="id" value="<?= $id; ?>">
        <input type="hidden" name="entityName" value="<?= $entityName; ?>">
        <input type="hidden" name="returnUrl" value="<?= $returnUrl; ?>">

        <div class="row">
            <div class="span1">
                Title
            </div>
            <div class="span11">
                <input type="text" maxlength="255" name="title">
            </div>
        </div>
        <div class="row">
            <div class="span1">
                URL
            </div>
            <div class="span11">
                <input type="text" maxlength="255" name="url">
            </div>
        </div>
        <div class="row">
            <div class="span1">
                Note
            </div>
            <div class="span11">
                <textarea name="note"></textarea>
            </div>
        </div>

        <div class="row">
            <div class="span1">
                &nbsp;
            </div>
            <div class="span11">
                <button class="btn btn-info" type="send">
                    <i class="icon-save"></i>
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>

