<li class="">
    <a onClick="$('#createPerformerAlias').toggle();"  class="btn-success" href="#"><i class="icon-film"></i> Create Performer Alias</a>
</li>

<div id="createPerformerAlias" style="display: none; clear:both;">

    <form method="post" action="/performer-alias/create">
        <div class="row">

            <div class="span1">
                Name
            </div>

            <div class="span11">
                <input type="text" name="name" maxlength="255">
            </div>
        </div>

        <div class="row">
            <div class="span1">
                Note
            </div>

            <div class="span11">
                <input type="hidden" name="id" value="<?= $id; ?>">
                <input type="hidden" name="entityName" value="<?= $entityName; ?>">
                <input type="hidden" name="returnUrl" value="<?= $returnUrl; ?>">
                <textarea name="note"></textarea>
                <br>
                <input type="submit" value="Submit">
            </div>

        </div>
    </form>
</div>
