<?php
use Zend\Form\Element;
use Zend\Form\Form;

$formElement = new Element\Text('band');
$formElement
    ->setLabel('<i class="icon-cogs"></i> ' . $this->label)
    ->setAttributes(array(
        'id' => 'band',
        'autocomplete' => 'off',
        'placeholder'  => '',
    ));

if ($band) {
    $formElement->setAttributes(array(
        'value' => $band->getName(),
    ));
}

?>

<?= $this->formRow($formElement); ?>

<input type="hidden" name="band_id" <?php if ($band) echo 'value="' . $band->getId() . '"'; ?> id="bandId"/>

<script>
var bands = {};
var bandLabels = [];

require(['modernizr.min', 'bootstrap.min', 'datemask', 'underscore-min'], function() {

    $( "#band" ).typeahead({
        source: function ( query, process ) {
            searchBands( query, process );
        }
        , updater: function (item) {
            //save the id value into the hidden field
            $( "#bandId" ).val( bands[ item ] );

            //return the string you want to go into the textbox (e.g. name)
            return item;
        }
        , matcher: function () { return true; }
    });

    var searchBands = _.debounce(function ( query, process ) {

        //the "process" argument is a callback, expecting an array of values (strings) to display

        //get the data to populate the typeahead (plus some)
        //from your api, wherever that may be
        $.get('/band/search-json', { q: query }, function ( data ) {

            //reset these containers
            bands = {};
            bandLabels = [];

            //for each item returned, if the display name is already included
            //(e.g. multiple "John Smith" records) then add a unique value to the end
            //so that the user can tell them apart. Using underscore.js for a functional approach.
            _.each( data.bands, function( item, ix, list ){

                if ( _.contains( bands, item.label ) ){
                    item.label = item.label + ' #' + item.value;
                }

                //add the label to the display array
                bandLabels.push( item.label );

                //also store a mapping to get from label back to ID
                bands[ item.label ] = item.value;
            });

            //return the display array
            process( bandLabels );
        });
    }, 300);

});
</script>