<?php
use Zend\Form\Element;
use Zend\Form\Form;

$id = md5(uniqid());
$formElement = new Element\Text('venue');
$formElement->setAttributes(array(
    'id' => 'data' . $id,
    'autocomplete' => 'off',
    'placeholder'  => '',
));

if ($this->label)
    $formElement->setLabel("<a class=\"btn btn-success create-venue\" href='#' title=\"Create Venue\"><i class=\"icon-map-marker\"></i> " . $this->label . "</a>");

if ($this->venue) {
    $formElement->setAttributes(array(
        'value' => $venue->getName(),
    ));
}

?>

<?= $this->formRow($formElement); ?>

<input type="hidden" name="venue_id" <?php if ($venue) echo 'value="' . $venue->getId() . '"'; ?> id="Id<?= $id; ?>"/>

<script>
var data<?= $id; ?> = {};
var dataLabels<?= $id; ?> = [];

require(['modernizr.min', 'bootstrap.min', 'datemask', 'underscore-min'], function() {

    $( "#data<?= $id; ?>" ).typeahead({
        source: function ( query, process ) {
            searchData<?= $id; ?>( query, process );
        }
        , updater: function (item) {
                $( "#Id<?= $id; ?>" ).val( data<?= $id; ?>[ item ].id );

            return item;
        }
        , matcher: function () { return true; }

        , highlighter: function(item){
            var p = data<?= $id; ?>[ item ];
            var liHtml = ''
                + "<div class='typeahead_wrapper'>"
                + "<div class='typeahead_labels'>"
                + "<div class='typeahead_primary'><b>" + p.name + "</b></div>"
                + "<div class='typeahead_secondary'>" + p.city + "</div>"
                + "<div class='typeahead_secondary'>" + p.state + "</div>"
                + "<div class='typeahead_secondary'>" + p.zipcode + "</div>"
                + "<div class='typeahead_secondary'>" + p.country + "</div>"
                + "</div>"
                + "</div>";
            return liHtml;
        }
    });

    var searchData<?= $id; ?> = _.debounce(function ( query, process ) {

        $.get('/venue/search-json', { q: query }, function (data) {

            data<?= $id; ?> = {};
            dataLabels<?= $id; ?> = [];

            _.each( data.venues, function( item, ix, list ){
                // Alias each item with id
                item.label = item.name + ' #' + item.id;

                data<?= $id; ?>[ item.label ] = item;
                dataLabels<?= $id; ?>.push( item.label );
            });

            process(dataLabels<?= $id; ?>);
        });
    }, 300);

});
</script>