<?php
use Zend\Form\Element;
use Zend\Form\Form;

$id = md5(uniqid());
$formElement = new Element\Text('venue');
$formElement
    ->setLabel('<i class="icon-map-marker"></i> ' . $this->label)
    ->setAttributes(array(
        'id' => 'venue' . $id,
        'autocomplete' => 'off',
        'placeholder'  => '',
    ));

if ($venue) {
    $formElement->setAttributes(array(
        'value' => $venue->getName(),
    ));
}

?>

<?= $this->formRow($formElement); ?>

<input type="hidden" name="venue_id" <?php if ($venue) echo 'value="' . $venue->getId() . '"'; ?> id="Id<?= $id; ?>"/>

<script>
var venues<?= $id; ?> = {};
var venueLabels<?= $id; ?> = [];

require(['modernizr.min', 'bootstrap.min', 'datemask', 'underscore-min'], function() {

    $( "#venue<?= $id; ?>" ).typeahead({
        source: function ( query, process ) {
            searchVenues<?= $id; ?>( query, process );
        }
        , updater: function (item) {
            //save the id value into the hidden field
            $( "#Id<?= $id; ?>" ).val( venues<?= $id; ?>[ item ] );

            //return the string you want to go into the textbox (e.g. name)
            return item;
        }
        , matcher: function () { return true; }
    });

    var searchVenues<?= $id; ?> = _.debounce(function ( query, process ) {

        //the "process" argument is a callback, expecting an array of values (strings) to display

        //get the data to populate the typeahead (plus some)
        //from your api, wherever that may be
        $.get('/venue/search-json', { q: query }, function ( data ) {

            //reset these containers
            venues<?= $id; ?> = {};
            venueLabels<?= $id; ?> = [];

            //for each item returned, if the display name is already included
            //(e.g. multiple "John Smith" records) then add a unique value to the end
            //so that the user can tell them apart. Using underscore.js for a functional approach.
            _.each( data.venues, function( item, ix, list ){

                if ( _.contains( venues<?= $id; ?>, item.label ) ){
                    item.label = item.label + ' #' + item.value;
                }

                //add the label to the display array
                venueLabels<?= $id; ?>.push( item.label );

                //also store a mapping to get from label back to ID
                venues<?= $id; ?>[ item.label ] = item.value;
            });

            //return the display array
            process(venueLabels<?= $id; ?>);
        });
    }, 300);

});
</script>