<?php
foreach ($this->links as $link) {
?>
    <blockquote>
        <a href="#" class="btn btn-warning edit-link" data-id="<?= $link->getId(); ?>">
            <i class="icon-external-link"></i>
        </a>

        <cite>
            <a class="btn btn-info" href="<?= $link->getUrl(); ?>">
                <i class="icon-external-link"></i>
            </a>
            <?= $this->escapeHtml($link->getTitle()); ?>
        </cite>

        <?php
        if ($link->getNote()) echo ' &middot; ';
        ?>

        <?= $this->escapeHtml($link->getNote()); ?>
    </blockquote>
<?php
}
?>
