<ul>

<?php
foreach ($performances as $performance) {
?>

<li>
    <a href="/performance/detail?id=<?= $performance->getId(); ?>">
    <i class="icon-magic"></i>
<?php
if ($performance->getPerformanceDateAt()->format('F d, Y') != 'September 1, 1939') {
    echo $this->escapeHtml($performance->getPerformanceDateAt()->format('F d, Y'));
} else {
    echo $this->escapeHtml($performance->getPerformanceDate());
}
?>
    </a>

    <?= $this->escapeHtml($performance->getName()); ?>

    <a href="/band/detail?id=<?= $performance->getLineup()->getBand()->getId(); ?>">
        <i class="icon-cogs"></i>
        <?= $this->escapeHtml($performance->getLineup()->getBand()->getName()); ?>
    </a>

    <a href="/venue/detail?id=<?= $performance->getVenue()->getId(); ?>">

        <i class="icon-map-marker"></i>
        <?= $this->escapeHtml($performance->getVenue()->getName()); ?>
    </a>
</h2>


<?php
}
