<h4>Comments</h4>

<?php
foreach ($comments as $comment) {
?>
    <hr>
    <div class="row">
        <div class="span2">

            <span class="rating">
                <span class="star" style="font-size: 16px;"></span>
                <span class="star" style="font-size: 16px;"></span>
                <span class="star" style="font-size: 16px;"></span>
                <span class="star" style="font-size: 16px;"></span>
                <span class="star" style="font-size: 16px;"></span>
            </span>

        <br>

        <?= $this->escapeHtml($comment->getCreatedAt()->format('r')); ?>

        </div>

        <div class="span10">

            <?php
            if ($this->zfcUserIdentity() == $comment->getUser()) {
            ?>

            <ul class="nav nav-pills pull-right">
                <li class="">
                   <a class="returnUrl btn-danger"
                       href="<?=
                        $this->url('comment/delete', array(
                            'id' => $comment->getId(),
                        )); ?>&entityName=<?= get_class($comment); ?>">
                       <i class="icon-comment"></i> Delete Comment
                   </a>
                </li>
            </ul>

            <?php
            }
            ?>

            <h5>
                <?= $this->escapeHtml($comment->getUser()->getDisplayName()); ?>
            </h5>

            <div style="border: solid; border-radius: 10px; border-color: gray; padding: 10px;">
                <?= $this->escapeHtml($comment->getNote()); ?>
            </div>
        </div>
    </div>
<?php
}
?>
