
<li>
    <a class="btn-danger" href="#" onClick="
//        $('#createPerformerPerformanceSpan').load('/performance/add-performer?id=<?= $this->id; ?>');
        $('#deletePerformerPerformanceSpan').modal();

        ">
        <i class="icon-film"></i>
        Remove
    </a>
</li>

<span class="modal hide" id="deletePerformerPerformanceSpan">
<form method="post" action="/performance/remove-performer?id=<?= $id; ?>">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>
        <i class="icon-film"></i>
        Add Performer to Performance
    </h3>
    </div>
    <div class="modal-body">

        <input type="hidden" name="id" value="<?= $id; ?>">
        <?= $this->inputPerformer(); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-danger">
            <i class="icon-"></i>
            Remove Performer from Performance
        </button>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>


    </div>
</form>
</span>
