<a class="pull-right btn-warning" href="/lineup/edit?id=<?= $this->lineup->getId(); ?>"><i class="icon-group"></i> Edit Performer Lineup</a>

<?= $this->partial(
    'db-etree-org/partial/workspace',
    array('entity' => $this->lineup)
);
?>


<h1><i class="icon-cogs"></i>
    <a href="/band/detail?id=<?= $this->lineup->getBand()->getId(); ?>">
        <?= $this->escapeHtml($this->lineup->getBand()->getName()); ?>
    </a>
</h1>

<h1>
    <i class="icon-group"></i>
    <?= $this->escapeHtml($this->lineup->getName()); ?>
</h1>

<?php
if ($this->lineup->getNote()) { ?>
    <pre><?= $this->escapeHtml($this->lineup->getNote()); ?></pre>
<?php
}
?>

<?php
foreach ($this->lineup->getPerformerLineups() as $performerLineup) {
?>
    <h3>
        &nbsp;&nbsp;&nbsp;
        <a href="/performer-lineup/detail?id=<?= $performerLineup->getId(); ?>">
            <i class="icon-film"></i>
            <?= $this->escapeHtml($performerLineup->getPerformer()->getName()); ?>
        </a>
    </h3>

    <?php
    if ($performerLineup->getNote()) {
    ?>
        <pre><?= $this->escapeHtml($performerLineup->getNote()); ?></pre>
    <?php
    }
    ?>

<?php
}
?>