<?php
$id = md5(uniqid());
?>

<?= $this->form()->openTag($form); ?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>
            <i class="icon-facetime-video"></i>
            Edit Guest Performer Performance
        </h1>
    </div>
    <div class="modal-body">

        <?= $this->formRow($this->form->get('note')); ?>

    </div>
    <div class="modal-footer">

        <button type="send" class="btn btn-warning">
            <i class="icon-facetime-video"></i>
            Edit Guest Performer Performance
        </button>

        <a class="confirm btn btn-danger" href="/performer-performance/delete?id=<?= $this->id; ?>">
            <i class="icon-facetime-video"></i>
            Remove Guest Performer from Performance
        </a>

        <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
            Cancel
        </button>

    </div>
<?= $this->form()->closeTag(); ?>

<script>

$(function() {
    $('form#performer-performance').attr('id', 'performer-performance<?= $id; ?>');
    $('form#performer-performance<?= $id; ?>').on('submit', function(event) {
        $.ajax({
            url: '/performer-performance/edit?id=<?= $this->performerPerformance->getId(); ?>',
            type: $(this).attr('method'),
            data: $(this).serialize(),
            span: $(this).closest('span'),
            success: function(data) {
                if (data) {
                    $(this.span).html(data);
                } else {
                    $(this.span).modal('hide');
                    document.location.reload();
                }
            }
        });

        return false;
    });
});

</script>