<?= $this->form()->openTag($form); ?>

<?= $this->formRow($this->form->get('displayName')); ?>

<?= $this->formRow($this->form->get('username')); ?>

<?= $this->formRow($this->form->get('email')); ?>

<?= $this->formRow($this->form->get('isPublic')); ?>

<?= $this->formRow($this->form->get('note')); ?>

<br>

<button type="send" class="btn btn-warning">
    <i class="icon-user"></i>
    Edit Profile  
</button>

<?= $this->form()->closeTag(); ?>
