<div class="row">
    <div class="span1">
        <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
    </div>
    <div class="span11">
        <ul class="nav nav-pills pull-right">
            <li class="">
                <a class="btn-warning" href="/user/edit">
                    <i class="icon-user"></i>
                    Edit Profile
                </a>
            </li>
        </ul>

        <h1><?php echo $this->zfcUserDisplayName() ?></h1>
    </div>
</div>

